-- =====================================================
-- ZelosHR (Human Resource) RBAC seed — core-platform navigation role-permissions
-- Reference data lives in core_platform (shared across modules).
-- Idempotent: re-run safe via ON CONFLICT. Runs every deploy.
-- Permission->role assignment is handled by the core_platform
-- auto-assign triggers (by resource-type hierarchy), same as loandrift/msg.
-- =====================================================

SET search_path TO core_platform;

-- App-specific permission->role mappings are created by the core_platform
-- auto-assign triggers (by resource-type hierarchy). Here we only add the
-- shared core-platform navigation permissions every HR role needs, exactly
-- like loandrift/mystoreguard 04_others.
INSERT INTO core_platform.cp_role_permissions (tenant_id, role_id, permission_id) VALUES
('system-tenant-id', 'role-subscribed-app-zeloshr-admin', 'permission-app-get'),
('system-tenant-id', 'role-subscribed-app-zeloshr-admin', 'permission-business-get'),
('system-tenant-id', 'role-subscribed-app-zeloshr-admin', 'permission-organization-get'),
('system-tenant-id', 'role-subscribed-app-zeloshr-admin', 'permission-business-app-get'),
('system-tenant-id', 'role-subscribed-app-zeloshr-admin', 'permission-business-app-get-locations'),
('system-tenant-id', 'role-subscribed-app-zeloshr-admin', 'permission-user-get-locations'),
('system-tenant-id', 'role-zeloshr-dashboard-admin', 'permission-app-get'),
('system-tenant-id', 'role-zeloshr-dashboard-admin', 'permission-business-get'),
('system-tenant-id', 'role-zeloshr-dashboard-admin', 'permission-organization-get'),
('system-tenant-id', 'role-zeloshr-dashboard-admin', 'permission-business-app-get'),
('system-tenant-id', 'role-zeloshr-dashboard-admin', 'permission-business-app-get-locations'),
('system-tenant-id', 'role-zeloshr-dashboard-admin', 'permission-user-get-locations'),
('system-tenant-id', 'role-zeloshr-employee-admin', 'permission-app-get'),
('system-tenant-id', 'role-zeloshr-employee-admin', 'permission-business-get'),
('system-tenant-id', 'role-zeloshr-employee-admin', 'permission-organization-get'),
('system-tenant-id', 'role-zeloshr-employee-admin', 'permission-business-app-get'),
('system-tenant-id', 'role-zeloshr-employee-admin', 'permission-business-app-get-locations'),
('system-tenant-id', 'role-zeloshr-employee-admin', 'permission-user-get-locations'),
('system-tenant-id', 'role-zeloshr-org-admin', 'permission-app-get'),
('system-tenant-id', 'role-zeloshr-org-admin', 'permission-business-get'),
('system-tenant-id', 'role-zeloshr-org-admin', 'permission-organization-get'),
('system-tenant-id', 'role-zeloshr-org-admin', 'permission-business-app-get'),
('system-tenant-id', 'role-zeloshr-org-admin', 'permission-business-app-get-locations'),
('system-tenant-id', 'role-zeloshr-org-admin', 'permission-user-get-locations'),
('system-tenant-id', 'role-zeloshr-departments-admin', 'permission-app-get'),
('system-tenant-id', 'role-zeloshr-departments-admin', 'permission-business-get'),
('system-tenant-id', 'role-zeloshr-departments-admin', 'permission-organization-get'),
('system-tenant-id', 'role-zeloshr-departments-admin', 'permission-business-app-get'),
('system-tenant-id', 'role-zeloshr-departments-admin', 'permission-business-app-get-locations'),
('system-tenant-id', 'role-zeloshr-departments-admin', 'permission-user-get-locations'),
('system-tenant-id', 'role-zeloshr-branches-admin', 'permission-app-get'),
('system-tenant-id', 'role-zeloshr-branches-admin', 'permission-business-get'),
('system-tenant-id', 'role-zeloshr-branches-admin', 'permission-organization-get'),
('system-tenant-id', 'role-zeloshr-branches-admin', 'permission-business-app-get'),
('system-tenant-id', 'role-zeloshr-branches-admin', 'permission-business-app-get-locations'),
('system-tenant-id', 'role-zeloshr-branches-admin', 'permission-user-get-locations'),
('system-tenant-id', 'role-zeloshr-lifecycle-admin', 'permission-app-get'),
('system-tenant-id', 'role-zeloshr-lifecycle-admin', 'permission-business-get'),
('system-tenant-id', 'role-zeloshr-lifecycle-admin', 'permission-organization-get'),
('system-tenant-id', 'role-zeloshr-lifecycle-admin', 'permission-business-app-get'),
('system-tenant-id', 'role-zeloshr-lifecycle-admin', 'permission-business-app-get-locations'),
('system-tenant-id', 'role-zeloshr-lifecycle-admin', 'permission-user-get-locations'),
('system-tenant-id', 'role-zeloshr-audit-admin', 'permission-app-get'),
('system-tenant-id', 'role-zeloshr-audit-admin', 'permission-business-get'),
('system-tenant-id', 'role-zeloshr-audit-admin', 'permission-organization-get'),
('system-tenant-id', 'role-zeloshr-audit-admin', 'permission-business-app-get'),
('system-tenant-id', 'role-zeloshr-audit-admin', 'permission-business-app-get-locations'),
('system-tenant-id', 'role-zeloshr-audit-admin', 'permission-user-get-locations'),
('system-tenant-id', 'role-zeloshr-attendance-admin', 'permission-app-get'),
('system-tenant-id', 'role-zeloshr-attendance-admin', 'permission-business-get'),
('system-tenant-id', 'role-zeloshr-attendance-admin', 'permission-organization-get'),
('system-tenant-id', 'role-zeloshr-attendance-admin', 'permission-business-app-get'),
('system-tenant-id', 'role-zeloshr-attendance-admin', 'permission-business-app-get-locations'),
('system-tenant-id', 'role-zeloshr-attendance-admin', 'permission-user-get-locations'),
('system-tenant-id', 'role-zeloshr-leave-admin', 'permission-app-get'),
('system-tenant-id', 'role-zeloshr-leave-admin', 'permission-business-get'),
('system-tenant-id', 'role-zeloshr-leave-admin', 'permission-organization-get'),
('system-tenant-id', 'role-zeloshr-leave-admin', 'permission-business-app-get'),
('system-tenant-id', 'role-zeloshr-leave-admin', 'permission-business-app-get-locations'),
('system-tenant-id', 'role-zeloshr-leave-admin', 'permission-user-get-locations'),
('system-tenant-id', 'role-zeloshr-recruitment-admin', 'permission-app-get'),
('system-tenant-id', 'role-zeloshr-recruitment-admin', 'permission-business-get'),
('system-tenant-id', 'role-zeloshr-recruitment-admin', 'permission-organization-get'),
('system-tenant-id', 'role-zeloshr-recruitment-admin', 'permission-business-app-get'),
('system-tenant-id', 'role-zeloshr-recruitment-admin', 'permission-business-app-get-locations'),
('system-tenant-id', 'role-zeloshr-recruitment-admin', 'permission-user-get-locations'),
('system-tenant-id', 'role-zeloshr-onboarding-admin', 'permission-app-get'),
('system-tenant-id', 'role-zeloshr-onboarding-admin', 'permission-business-get'),
('system-tenant-id', 'role-zeloshr-onboarding-admin', 'permission-organization-get'),
('system-tenant-id', 'role-zeloshr-onboarding-admin', 'permission-business-app-get'),
('system-tenant-id', 'role-zeloshr-onboarding-admin', 'permission-business-app-get-locations'),
('system-tenant-id', 'role-zeloshr-onboarding-admin', 'permission-user-get-locations'),
('system-tenant-id', 'role-zeloshr-performance-admin', 'permission-app-get'),
('system-tenant-id', 'role-zeloshr-performance-admin', 'permission-business-get'),
('system-tenant-id', 'role-zeloshr-performance-admin', 'permission-organization-get'),
('system-tenant-id', 'role-zeloshr-performance-admin', 'permission-business-app-get'),
('system-tenant-id', 'role-zeloshr-performance-admin', 'permission-business-app-get-locations'),
('system-tenant-id', 'role-zeloshr-performance-admin', 'permission-user-get-locations'),
('system-tenant-id', 'role-zeloshr-disciplinary-admin', 'permission-app-get'),
('system-tenant-id', 'role-zeloshr-disciplinary-admin', 'permission-business-get'),
('system-tenant-id', 'role-zeloshr-disciplinary-admin', 'permission-organization-get'),
('system-tenant-id', 'role-zeloshr-disciplinary-admin', 'permission-business-app-get'),
('system-tenant-id', 'role-zeloshr-disciplinary-admin', 'permission-business-app-get-locations'),
('system-tenant-id', 'role-zeloshr-disciplinary-admin', 'permission-user-get-locations'),
('system-tenant-id', 'role-zeloshr-documents-admin', 'permission-app-get'),
('system-tenant-id', 'role-zeloshr-documents-admin', 'permission-business-get'),
('system-tenant-id', 'role-zeloshr-documents-admin', 'permission-organization-get'),
('system-tenant-id', 'role-zeloshr-documents-admin', 'permission-business-app-get'),
('system-tenant-id', 'role-zeloshr-documents-admin', 'permission-business-app-get-locations'),
('system-tenant-id', 'role-zeloshr-documents-admin', 'permission-user-get-locations'),
('system-tenant-id', 'role-zeloshr-custom-fields-admin', 'permission-app-get'),
('system-tenant-id', 'role-zeloshr-custom-fields-admin', 'permission-business-get'),
('system-tenant-id', 'role-zeloshr-custom-fields-admin', 'permission-organization-get'),
('system-tenant-id', 'role-zeloshr-custom-fields-admin', 'permission-business-app-get'),
('system-tenant-id', 'role-zeloshr-custom-fields-admin', 'permission-business-app-get-locations'),
('system-tenant-id', 'role-zeloshr-custom-fields-admin', 'permission-user-get-locations')
ON CONFLICT (tenant_id, role_id, permission_id) DO NOTHING;
