<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Trovesuite.Database.HumanResource</RootNamespace>
    <AssemblyName>Trovesuite.Database.HumanResource</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Trovesuite.Database.Common\Trovesuite.Database.Common.csproj" />
    <ProjectReference Include="..\Trovesuite.Database.CorePlatform\Trovesuite.Database.CorePlatform.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Sql\**\*.sql" />
  </ItemGroup>
</Project>
