#!/usr/bin/env python3
"""Generate an app's permission module from core_platform.cp_permissions.

A permission id is an opaque string with its parts baked in, so a wrong one is invisible:
`permission-msg-clients-get` sat in a frontend map for months naming something that never
existed, and eleven Core Platform endpoints were gated on ids that had been replaced. The
generated module makes the (resource, action) pair the address and the id a lookup, so a
resource or verb that does not exist is an AttributeError or a KeyError at the call site
rather than a check that quietly matches nothing.

Usage:

    export DATABASE_URL='postgresql://user:pass@host:5432/db?sslmode=require'
    scripts/gen_permissions_module.py --app msg \
        --out ../../mystoreguard/tvs-mystoreguard-bk/app/src/utils/permissions.py

    # Core Platform owns two prefixes: its own ('') and the 'cp' ones.
    scripts/gen_permissions_module.py --app '' --app cp \
        --out ../../coreplatform/tvs-coreplatform-bk/app/src/utils/permissions.py

    # A .NET app: nested classes per resource, because its call sites are attributes.
    scripts/gen_permissions_module.py --app zeloshr --lang csharp \
        --namespace ZelosHR.Api.Shared.Authorization --class-name ZelosHrPermissions \
        --out ../../zeloshr/tvs-zeloshr-admin-bk/app/src/Shared/Authorization/ZelosHrPermissions.cs

Re-run after changing the resource catalogue (cp_resources / cp_permission_overrides). The
app logs a startup ERROR when its module has gone stale, so drift announces itself, but
regenerating is how you fix it.
"""
import argparse, os, re, sys

LABEL = {"": "Core Platform", "cp": "Core Platform", "msg": "MyStoreGuard",
         "loandrift": "LoanDrift", "zeloshr": "ZelosHR"}


def pair_key(r: dict) -> str:
    """What a permission is CALLED once it is named by what it grants.

    Must match AuthService.pair_key in tvs-package and AuthService.PairKey in
    tvs-package-dotnet exactly, separator included; the three meet on this string and
    nowhere else.
    """
    return "|".join([r["app_prefix"] or "", r["resource_key"], r["action"],
                     r["target"] or "", r["scope"] or "any"])


def const(value: str) -> str:
    return re.sub(r"[^A-Z0-9]+", "_", value.upper()).strip("_")


def fetch(dsn: str, prefixes: list[str], also: list[str] | None = None):
    """Every permission for these app prefixes, plus any named outright.

    `also` exists for the handful of permissions an app ENFORCES but does not own. Currency is
    the real one: MyStoreGuard and LoanDrift both check permission-currency-get when listing
    currencies, and the currencies belong to Core Platform, so its app_prefix is ''. Without
    this the id had to be written as a string in four controllers -- the one kind of call site
    the generated module exists to abolish, and the kind that fails silently when the id moves.
    """
    import psycopg2, psycopg2.extras
    with psycopg2.connect(dsn) as conn, conn.cursor(
        cursor_factory=psycopg2.extras.RealDictCursor
    ) as cur:
        cur.execute(
            """SELECT id, app_prefix, resource_key, action, target, scope
               FROM core_platform.cp_permissions
               WHERE delete_status = 'NOT_DELETED' AND is_active = true
                 AND (app_prefix = ANY(%s) OR id = ANY(%s))
               ORDER BY resource_key, action, target, scope""",
            (prefixes, list(also or [])),
        )
        rows = [dict(r) for r in cur.fetchall()]

    # A name that matches nothing is a typo in the deploy command, and silently generating a
    # module without it would put the silent-refusal bug straight back.
    found = {r["id"] for r in rows}
    missing = [i for i in (also or []) if i not in found]
    if missing:
        sys.exit(f"--also-include names permissions that do not exist: {', '.join(missing)}")
    return rows


def render(rows, prefixes) -> str:
    resources = sorted({r["resource_key"] for r in rows})
    actions = sorted({r["action"] for r in rows})
    targets = sorted({r["target"] for r in rows if r["target"]})
    if not rows:
        sys.exit(f"no permissions found for app_prefix {prefixes!r}")

    def block(names):
        width = max(len(const(n)) for n in names)
        return "\n".join(f'    {const(n):<{width}} = "{n}"' for n in names)

    entries = "\n".join(
        f'    ("{r["resource_key"]}", "{r["action"]}", "{r["target"]}", "{r["scope"]}"): '
        f'"{pair_key(r)}",'
        for r in rows
    )
    id_entries = "\n".join(
        f'    ("{r["resource_key"]}", "{r["action"]}", "{r["target"]}", "{r["scope"]}"): '
        f'"{r["id"]}",'
        for r in rows
    )
    app = LABEL.get(prefixes[0], prefixes[0] or "Core Platform")
    return f'''"""{app} permission ids, addressed as (resource, action).

GENERATED by tvs-sqlscript/scripts/gen_permissions_module.py -- do not hand-edit. Regenerate
after changing the resource catalogue (cp_resources / cp_permission_overrides).

    from src.utils.permissions import A, R, T, perm

    perm(R.{const(resources[0])}, A.{const(actions[0])})

A resource or verb that does not exist is an AttributeError; a pair that does not is a
KeyError naming what that resource supports. Neither can become a check that silently
matches nothing.

This is also the seam for moving off id strings: when grants are stored as (resource,
action), perm() changes and its callers do not.

{len(rows)} permissions, {len(resources)} resources, {len(actions)} actions.
"""

from typing import Dict, Tuple


class R:
    """Resources."""

{block(resources)}


class A:
    """Actions. is_read_only / viewer_default live in core_platform.cp_actions."""

{block(actions)}


class T:
    """Targets -- what a verb acts upon, where the verb alone is ambiguous.

    Assigning a ROLE is not the same permission as assigning a LOCATION; the first is how
    somebody becomes an Owner.
    """

{block(targets) if targets else "    pass"}


#: What a permission is CALLED when it is named by what it grants:
#: "msg|store-sales|create||any" -- app, resource, verb, target, scope. This is what the
#: check compares, and what tvs-package puts in a user's permission set alongside the id.
_PERMISSIONS: Dict[Tuple[str, str, str, str], str] = {{
{entries}
}}

#: The same permissions by their database id. Nothing in an endpoint should need these --
#: they are here for the boot-time audit, which compares this module against
#: core_platform.cp_permissions and can only do that by id.
_PERMISSION_IDS: Dict[Tuple[str, str, str, str], str] = {{
{id_entries}
}}


def perm(resource: str, action: str, target: str = "", scope: str = "any") -> str:
    """What a (resource, action[, target][, scope]) is called in a permission check.

    Returns the pair -- "msg|store-sales|create||any" -- not the database id. The id still
    exists and still keys the row; it simply stopped being the thing a check compares, so a
    permission is now addressed by what it allows.
    """
    try:
        return _PERMISSIONS[(resource, action, target, scope)]
    except KeyError:
        near = sorted(
            f"{{a}}" + (f"+{{t}}" if t else "") + ("" if s == "any" else f"@{{s}}")
            for (r, a, t, s) in _PERMISSIONS
            if r == resource
        )
        if not near:
            raise KeyError(
                f"no permissions for resource {{resource!r}}; known resources: "
                f"{{', '.join(sorted({{r for r, _, _, _ in _PERMISSIONS}}))}}"
            ) from None
        raise KeyError(
            f"no permission for {{resource!r}} + {{action!r}}"
            + (f" + target {{target!r}}" if target else "")
            + ("" if scope == "any" else f" @ {{scope}}")
            + f"; {{resource!r}} supports: {{', '.join(near)}}"
        ) from None


def perm_id(resource: str, action: str, target: str = "", scope: str = "any") -> str:
    """The database id, for the audit and for nothing else."""
    return _PERMISSION_IDS[(resource, action, target, scope)]


ALL_PERMISSION_IDS = frozenset(_PERMISSION_IDS.values())
ALL_PERMISSION_KEYS = frozenset(_PERMISSIONS.values())
'''


def pascal(value: str) -> str:
    """`custom-field-values` -> `CustomFieldValues`."""
    return "".join(w[:1].upper() + w[1:] for w in re.split(r"[^A-Za-z0-9]+", value) if w)


def member(r: dict) -> str:
    """What a permission is called on the class of its resource.

    The verb, then the target and the scope when they are what distinguishes it:
    `Assign` and `AssignRoles` are different permissions, and so are `Get` and `GetOwn`.
    """
    name = pascal(r["action"])
    if r["target"]:
        name += pascal(r["target"])
    if (r["scope"] or "any") != "any":
        name += pascal(r["scope"])
    return name


def render_csharp(rows, prefixes, namespace: str, class_name: str) -> str:
    """The same catalogue as a C# class, for a .NET app.

    Nested classes per resource rather than one flat list of names, because every call site
    in a .NET app is an attribute argument -- [RequiresZelosHrPermission(...)] -- and an
    attribute argument must be a compile-time constant. A `perm(R.LEAVE, A.GET)` call like
    the Python module's cannot go there.

    So the resource is a class and the verb a const on it: `Leave.Get`. That reads as the
    pair, the same way `perm(R.LEAVE, A.GET)` does, and it is checked harder than Python
    manages -- a resource or verb that does not exist is a build error, not a KeyError at
    the moment somebody hits the endpoint. It also makes a misuse legible: a countries
    endpoint gated on `Leave.Get` says what it is doing.
    """
    if not rows:
        sys.exit(f"no permissions found for app_prefix {prefixes!r}")

    by_resource: dict[str, list[dict]] = {}
    for r in rows:
        by_resource.setdefault(r["resource_key"], []).append(r)

    app = LABEL.get(prefixes[0], prefixes[0] or "Core Platform")
    blocks = []
    for resource in sorted(by_resource):
        perms = sorted(by_resource[resource], key=member)
        width = max(len(member(r)) for r in perms)
        lines = "\n".join(
            f'        public const string {member(r):<{width}} = "{pair_key(r)}";'
            for r in perms
        )
        blocks.append(
            f'    /// <summary>{resource}</summary>\n'
            f'    public static class {pascal(resource)}\n'
            f'    {{\n{lines}\n    }}'
        )
    body = "\n\n".join(blocks)

    ids = "\n".join(
        f'        ["{pair_key(r)}"] = "{r["id"]}",' for r in rows
    )
    first = sorted(by_resource)[0]
    example = f'{pascal(first)}.{member(sorted(by_resource[first], key=member)[0])}'

    return f"""// GENERATED by tvs-sqlscript/scripts/gen_permissions_module.py -- do not hand-edit.
// Regenerate after changing the resource catalogue (cp_resources / cp_permission_overrides).
//
// {len(rows)} permissions across {len(by_resource)} resources.

namespace {namespace};

/// <summary>What {app} checks, addressed as (resource, verb).</summary>
/// <remarks>
/// Each const is the permission's PAIR -- "zeloshr|employee|get||any": app, resource, verb,
/// target, scope -- and not its database id. The id still keys the row in cp_permissions; it
/// simply stopped being the thing a check compares, so a permission is now named by what it
/// allows. tvs-package puts both names in a user's permission set, and the role rules
/// (Owner, Admin, an app's own admin) can only be applied to the pair, because only the pair
/// says which app a permission belongs to.
///
/// Held as nested classes because every call site is an attribute argument and those must be
/// compile-time constants:
///
///     [RequiresZelosHrPermission({class_name}.{example})]
///
/// A resource or verb that does not exist is a build error. The hand-written ids this
/// replaced could not be checked at all -- `permission-msg-clients-get` sat in a frontend
/// map for months naming a permission that never existed.
/// </remarks>
public static class {class_name}
{{
{body}

    /// <summary>Each pair's database id.</summary>
    /// <remarks>
    /// Declared before AllKeys, which is built from it: static field initializers run in
    /// declaration order, so the other way round AllKeys is built from a null dictionary and
    /// the whole class throws the first time anything touches it.
    ///
    /// An endpoint must never reach for one of these -- a check compares the pair. They are
    /// here so the boot-time audit can name the row a stale constant was pointing at.
    /// </remarks>
    public static readonly IReadOnlyDictionary<string, string> IdsByKey = new Dictionary<string, string>(StringComparer.Ordinal)
    {{
{ids}
    }};

    /// <summary>Every pair this app knows, for the boot-time catalogue audit.</summary>
    public static readonly IReadOnlySet<string> AllKeys = new HashSet<string>(IdsByKey.Keys, StringComparer.Ordinal);
}}
"""


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--app", action="append", required=True,
                    help="app_prefix to include; repeat for more than one ('' for Core Platform)")
    ap.add_argument("--also-include", action="append", default=[], metavar="PERMISSION_ID",
                    help="a permission this app enforces but does not own, e.g. "
                         "permission-currency-get; repeatable")
    ap.add_argument("--out", required=True, help="path of the module to write")
    ap.add_argument("--lang", choices=["python", "csharp"], default="python",
                    help="what to emit; csharp for a .NET app (default: python)")
    ap.add_argument("--namespace", default=None,
                    help="C# namespace, e.g. ZelosHR.Api.Shared.Authorization")
    ap.add_argument("--class-name", default=None,
                    help="C# class name, e.g. ZelosHrPermissions")
    ap.add_argument("--dsn", default=os.environ.get("DATABASE_URL"),
                    help="Postgres DSN (defaults to $DATABASE_URL)")
    args = ap.parse_args()
    if not args.dsn:
        sys.exit("no DSN: pass --dsn or set DATABASE_URL")

    if args.lang == "csharp" and not (args.namespace and args.class_name):
        sys.exit("--lang csharp needs --namespace and --class-name")

    rows = fetch(args.dsn, args.app, args.also_include)
    text = (render_csharp(rows, args.app, args.namespace, args.class_name)
            if args.lang == "csharp" else render(rows, args.app))
    with open(args.out, "w") as fh:
        fh.write(text)
    print(f"{args.out}: {len(rows)} permissions for app_prefix {args.app!r}")


if __name__ == "__main__":
    main()
