#!/usr/bin/env python3
"""Generate an app's permission module from core_platform.cp_permissions.

A permission id is an opaque string with its parts baked in, so a wrong one is invisible:
`permission-msg-clients-get` sat in a frontend map for months naming something that never
existed, and eleven Core Platform endpoints were gated on ids that had been replaced. The
generated module makes the (resource, action) pair the address and the id a lookup, so a
resource or verb that does not exist is an AttributeError or a KeyError at the call site
rather than a check that quietly matches nothing.

Usage:

    export DATABASE_URL='postgresql://user:pass@host:5432/db?sslmode=require'
    scripts/gen_permissions_module.py --app msg \
        --out ../../mystoreguard/tvs-mystoreguard-bk/app/src/utils/permissions.py

    # Core Platform owns two prefixes: its own ('') and the 'cp' ones.
    scripts/gen_permissions_module.py --app '' --app cp \
        --out ../../coreplatform/tvs-coreplatform-bk/app/src/utils/permissions.py

Re-run after changing the resource catalogue (cp_resources / cp_permission_overrides). The
app logs a startup ERROR when its module has gone stale, so drift announces itself, but
regenerating is how you fix it.
"""
import argparse, os, re, sys

LABEL = {"": "Core Platform", "cp": "Core Platform", "msg": "MyStoreGuard",
         "loandrift": "LoanDrift", "zeloshr": "ZelosHR"}


def const(value: str) -> str:
    return re.sub(r"[^A-Z0-9]+", "_", value.upper()).strip("_")


def fetch(dsn: str, prefixes: list[str]):
    import psycopg2, psycopg2.extras
    with psycopg2.connect(dsn) as conn, conn.cursor(
        cursor_factory=psycopg2.extras.RealDictCursor
    ) as cur:
        cur.execute(
            """SELECT id, app_prefix, resource_key, action, target, scope
               FROM core_platform.cp_permissions
               WHERE delete_status = 'NOT_DELETED' AND is_active = true
                 AND app_prefix = ANY(%s)
               ORDER BY resource_key, action, target, scope""",
            (prefixes,),
        )
        return [dict(r) for r in cur.fetchall()]


def render(rows, prefixes) -> str:
    resources = sorted({r["resource_key"] for r in rows})
    actions = sorted({r["action"] for r in rows})
    targets = sorted({r["target"] for r in rows if r["target"]})
    if not rows:
        sys.exit(f"no permissions found for app_prefix {prefixes!r}")

    def block(names):
        width = max(len(const(n)) for n in names)
        return "\n".join(f'    {const(n):<{width}} = "{n}"' for n in names)

    entries = "\n".join(
        f'    ("{r["resource_key"]}", "{r["action"]}", "{r["target"]}", "{r["scope"]}"): "{r["id"]}",'
        for r in rows
    )
    app = LABEL.get(prefixes[0], prefixes[0] or "Core Platform")
    return f'''"""{app} permission ids, addressed as (resource, action).

GENERATED by tvs-sqlscript/scripts/gen_permissions_module.py -- do not hand-edit. Regenerate
after changing the resource catalogue (cp_resources / cp_permission_overrides).

    from src.utils.permissions import A, R, T, perm

    perm(R.{const(resources[0])}, A.{const(actions[0])})

A resource or verb that does not exist is an AttributeError; a pair that does not is a
KeyError naming what that resource supports. Neither can become a check that silently
matches nothing.

This is also the seam for moving off id strings: when grants are stored as (resource,
action), perm() changes and its callers do not.

{len(rows)} permissions, {len(resources)} resources, {len(actions)} actions.
"""

from typing import Dict, Tuple


class R:
    """Resources."""

{block(resources)}


class A:
    """Actions. is_read_only / viewer_default live in core_platform.cp_actions."""

{block(actions)}


class T:
    """Targets -- what a verb acts upon, where the verb alone is ambiguous.

    Assigning a ROLE is not the same permission as assigning a LOCATION; the first is how
    somebody becomes an Owner.
    """

{block(targets) if targets else "    pass"}


_PERMISSIONS: Dict[Tuple[str, str, str, str], str] = {{
{entries}
}}


def perm(resource: str, action: str, target: str = "", scope: str = "any") -> str:
    """The permission id for a (resource, action[, target][, scope])."""
    try:
        return _PERMISSIONS[(resource, action, target, scope)]
    except KeyError:
        near = sorted(
            f"{{a}}" + (f"+{{t}}" if t else "") + ("" if s == "any" else f"@{{s}}")
            for (r, a, t, s) in _PERMISSIONS
            if r == resource
        )
        if not near:
            raise KeyError(
                f"no permissions for resource {{resource!r}}; known resources: "
                f"{{', '.join(sorted({{r for r, _, _, _ in _PERMISSIONS}}))}}"
            ) from None
        raise KeyError(
            f"no permission for {{resource!r}} + {{action!r}}"
            + (f" + target {{target!r}}" if target else "")
            + ("" if scope == "any" else f" @ {{scope}}")
            + f"; {{resource!r}} supports: {{', '.join(near)}}"
        ) from None


ALL_PERMISSION_IDS = frozenset(_PERMISSIONS.values())
'''


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--app", action="append", required=True,
                    help="app_prefix to include; repeat for more than one ('' for Core Platform)")
    ap.add_argument("--out", required=True, help="path of the module to write")
    ap.add_argument("--dsn", default=os.environ.get("DATABASE_URL"),
                    help="Postgres DSN (defaults to $DATABASE_URL)")
    args = ap.parse_args()
    if not args.dsn:
        sys.exit("no DSN: pass --dsn or set DATABASE_URL")

    rows = fetch(args.dsn, args.app)
    with open(args.out, "w") as fh:
        fh.write(render(rows, args.app))
    print(f"{args.out}: {len(rows)} permissions for app_prefix {args.app!r}")


if __name__ == "__main__":
    main()
