// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Trovesuite.Database.HumanResource;

#nullable disable

namespace Trovesuite.Database.HumanResource.Migrations
{
    [DbContext(typeof(HumanResourceDbContext))]
    [Migration("20260720140000_MakeZhrCompanyProfileLegalNameNullable")]
    partial class MakeZhrCompanyProfileLegalNameNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            // Apply-only migration; final model state lives in HumanResourceDbContextModelSnapshot.
#pragma warning restore 612, 618
        }
    }
}
