// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Trovesuite.Database.HumanResource;

#nullable disable

namespace Trovesuite.Database.HumanResource.Migrations
{
    [DbContext(typeof(HumanResourceDbContext))]
    partial class HumanResourceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("human_resource")
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Trovesuite.Database.CorePlatform.Entities.Business", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("TenantId")
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<string>("BusName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bus_name");

                    b.Property<string>("Cdate")
                        .HasColumnType("text")
                        .HasColumnName("cdate");

                    b.Property<DateTimeOffset?>("Cdatetime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cdatetime");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Ctime")
                        .HasColumnType("text")
                        .HasColumnName("ctime");

                    b.Property<string>("DeleteStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("delete_status");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LogoId")
                        .HasColumnType("text")
                        .HasColumnName("logo_id");

                    b.Property<string>("OrgId")
                        .HasColumnType("text")
                        .HasColumnName("org_id");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id", "TenantId")
                        .HasName("pk_cp_businesses");

                    b.ToTable("cp_businesses", "core_platform", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Trovesuite.Database.CorePlatform.Entities.Currency", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("TenantId")
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Cdate")
                        .HasColumnType("text")
                        .HasColumnName("cdate");

                    b.Property<DateTimeOffset?>("Cdatetime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cdatetime");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Country")
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Ctime")
                        .HasColumnType("text")
                        .HasColumnName("ctime");

                    b.Property<string>("CurrencyPosition")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currency_position");

                    b.Property<int>("DecimalPlaces")
                        .HasColumnType("integer")
                        .HasColumnName("decimal_places");

                    b.Property<string>("DecimalSeparator")
                        .HasColumnType("text")
                        .HasColumnName("decimal_separator");

                    b.Property<string>("DeleteStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("delete_status");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<decimal?>("ExchangeRate")
                        .HasColumnType("numeric")
                        .HasColumnName("exchange_rate");

                    b.Property<string>("ExchangeRateSource")
                        .HasColumnType("text")
                        .HasColumnName("exchange_rate_source");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<string>("Locale")
                        .HasColumnType("text")
                        .HasColumnName("locale");

                    b.Property<string>("MinorUnitName")
                        .HasColumnType("text")
                        .HasColumnName("minor_unit_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("symbol");

                    b.Property<string>("ThousandSeparator")
                        .HasColumnType("text")
                        .HasColumnName("thousand_separator");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id", "TenantId")
                        .HasName("pk_cp_currencies");

                    b.ToTable("cp_currencies", "core_platform", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Trovesuite.Database.CorePlatform.Entities.Location", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("TenantId")
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Cdate")
                        .HasColumnType("text")
                        .HasColumnName("cdate");

                    b.Property<DateTimeOffset?>("Cdatetime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cdatetime");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Ctime")
                        .HasColumnType("text")
                        .HasColumnName("ctime");

                    b.Property<string>("DeleteStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("delete_status");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LocName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("loc_name");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id", "TenantId")
                        .HasName("pk_cp_locations");

                    b.ToTable("cp_locations", "core_platform", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Trovesuite.Database.CorePlatform.Entities.Organization", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("TenantId")
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Cdate")
                        .HasColumnType("text")
                        .HasColumnName("cdate");

                    b.Property<DateTimeOffset?>("Cdatetime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cdatetime");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Ctime")
                        .HasColumnType("text")
                        .HasColumnName("ctime");

                    b.Property<string>("DeleteStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("delete_status");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LogoId")
                        .HasColumnType("text")
                        .HasColumnName("logo_id");

                    b.Property<string>("OrgName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("org_name");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id", "TenantId")
                        .HasName("pk_cp_organizations");

                    b.ToTable("cp_organizations", "core_platform", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Trovesuite.Database.CorePlatform.Entities.ResourceType", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Cdate")
                        .HasColumnType("text")
                        .HasColumnName("cdate");

                    b.Property<DateTimeOffset?>("Cdatetime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cdatetime");

                    b.Property<string>("Ctime")
                        .HasColumnType("text")
                        .HasColumnName("ctime");

                    b.Property<string>("DeleteStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("delete_status");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("ParentResourceId")
                        .HasColumnType("text")
                        .HasColumnName("parent_resource_id");

                    b.Property<string>("ResourceTypeName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("resource_type_name");

                    b.HasKey("Id")
                        .HasName("pk_cp_resource_types");

                    b.ToTable("cp_resource_types", "core_platform", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Trovesuite.Database.CorePlatform.Entities.Tenant", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Cdate")
                        .HasColumnType("text")
                        .HasColumnName("cdate");

                    b.Property<DateTimeOffset?>("Cdatetime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cdatetime");

                    b.Property<string>("Ctime")
                        .HasColumnType("text")
                        .HasColumnName("ctime");

                    b.Property<string>("DeleteStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("delete_status");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_verified");

                    b.HasKey("Id")
                        .HasName("pk_cp_tenants");

                    b.ToTable("cp_tenants", "core_platform", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Trovesuite.Database.CorePlatform.Entities.UnitOfMeasure", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("TenantId")
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Cdate")
                        .HasColumnType("text")
                        .HasColumnName("cdate");

                    b.Property<DateTimeOffset?>("Cdatetime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cdatetime");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Ctime")
                        .HasColumnType("text")
                        .HasColumnName("ctime");

                    b.Property<decimal>("DecimalPlace")
                        .HasColumnType("numeric")
                        .HasColumnName("decimal_place");

                    b.Property<string>("DeleteStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("delete_status");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("symbol");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id", "TenantId")
                        .HasName("pk_cp_unit_of_measures");

                    b.ToTable("cp_unit_of_measures", "core_platform", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Trovesuite.Database.CorePlatform.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("TenantId")
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<bool>("CanLogin")
                        .HasColumnType("boolean")
                        .HasColumnName("can_login");

                    b.Property<string>("Cdate")
                        .HasColumnType("text")
                        .HasColumnName("cdate");

                    b.Property<DateTimeOffset?>("Cdatetime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cdatetime");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contact");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Ctime")
                        .HasColumnType("text")
                        .HasColumnName("ctime");

                    b.Property<string>("DeleteStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("delete_status");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Dob")
                        .HasColumnType("text")
                        .HasColumnName("dob");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fullname");

                    b.Property<string>("Gender")
                        .HasColumnType("text")
                        .HasColumnName("gender");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsOwner")
                        .HasColumnType("boolean")
                        .HasColumnName("is_owner");

                    b.Property<string>("LoginPassword")
                        .HasColumnType("text")
                        .HasColumnName("login_password");

                    b.Property<string>("ProfilePic")
                        .HasColumnType("text")
                        .HasColumnName("profile_pic");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id", "TenantId")
                        .HasName("pk_cp_users");

                    b.ToTable("cp_users", "core_platform", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Trovesuite.Database.HumanResource.Entities.Employee", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()::text");

                    b.Property<string>("TenantId")
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Cdate")
                        .HasColumnType("text")
                        .HasColumnName("cdate");

                    b.Property<DateTimeOffset?>("Cdatetime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("cdatetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Ctime")
                        .HasColumnType("text")
                        .HasColumnName("ctime");

                    b.Property<string>("DeleteStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("NOT_DELETED")
                        .HasColumnName("delete_status");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id", "TenantId")
                        .HasName("pk_hr_employees");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_hr_employees_tenant_id");

                    b.HasIndex("CreatedBy", "TenantId")
                        .HasDatabaseName("ix_hr_employees_created_by_tenant_id");

                    b.HasIndex("DeletedBy", "TenantId")
                        .HasDatabaseName("ix_hr_employees_deleted_by_tenant_id");

                    b.HasIndex("UpdatedBy", "TenantId")
                        .HasDatabaseName("ix_hr_employees_updated_by_tenant_id");

                    b.HasIndex("UserId", "TenantId")
                        .IsUnique()
                        .HasDatabaseName("ix_hr_employees_user_id_tenant_id");

                    b.ToTable("hr_employees", "human_resource", t =>
                        {
                            t.HasCheckConstraint("ck_hr_employees_delete_status", "delete_status IN ('PENDING','DELETED','NOT_DELETED')");
                        });
                });

            modelBuilder.Entity("Trovesuite.Database.HumanResource.Entities.Employee", b =>
                {
                    b.HasOne("Trovesuite.Database.CorePlatform.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_hr_employees_cp_tenants_tenant_id");

                    b.HasOne("Trovesuite.Database.CorePlatform.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy", "TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_hr_employees_cp_users_created_by_tenant_id");

                    b.HasOne("Trovesuite.Database.CorePlatform.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("DeletedBy", "TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_hr_employees_cp_users_deleted_by_tenant_id");

                    b.HasOne("Trovesuite.Database.CorePlatform.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedBy", "TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_hr_employees_cp_users_updated_by_tenant_id");

                    b.HasOne("Trovesuite.Database.CorePlatform.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId", "TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_hr_employees_cp_users_user_id_tenant_id");
                });
#pragma warning restore 612, 618
        }
    }
}
