<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Trovesuite.Database.Runner</RootNamespace>
    <AssemblyName>tvs-db</AssemblyName>
    <UserSecretsId>trovesuite-database-runner</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Trovesuite.Database.Common\Trovesuite.Database.Common.csproj" />
    <ProjectReference Include="..\Trovesuite.Database.CorePlatform\Trovesuite.Database.CorePlatform.csproj" />
    <ProjectReference Include="..\Trovesuite.Database.LoanDrift\Trovesuite.Database.LoanDrift.csproj" />
    <ProjectReference Include="..\Trovesuite.Database.MyStoreGuard\Trovesuite.Database.MyStoreGuard.csproj" />
    <ProjectReference Include="..\Trovesuite.Database.HumanResource\Trovesuite.Database.HumanResource.csproj" />
  </ItemGroup>
</Project>
