-- =====================================================================================
-- The first two rows in this table that are not POOLED.
--
-- Everything until now has been POOLED with a NULL tenant_id, because a pooled address
-- serves every tenant and the token says which. These two name a tenant and a database,
-- which is what the whole control plane was built to express -- and until trovesuite
-- 1.0.55 nothing could act on them, because a connection went to the pod's own database
-- whatever the row said.
--
--   siloshared.dev.trovesuite.com     SILO_SHARED
--       own DATABASE on the shared server, own CONTAINERS in the shared storage account
--
--   silodedicated.dev.trovesuite.com  SILO_DEDICATED
--       own SERVER, own STORAGE ACCOUNT
--
-- Own database means own containers; own server means its own storage account. The two
-- always move together, which is why storage_account and container_prefix sit beside the
-- db columns rather than in a table of their own. Each tier sets exactly ONE of them:
-- a shared silo prefixes containers inside each APP's own account, a dedicated silo owns
-- an account outright.
--
-- DEV TEST ROWS. Both point at databases created on 2026-10-02 and tagged
-- disposable=true; the tenant ids are invented and own no real data. They exist so the
-- tier can be exercised against real infrastructure rather than asserted.
--
-- db_secret_uri is a Key Vault URI, never a credential. The pod's managed identity is
-- what may read it -- which is why this table can be readable to every app without being
-- worth stealing. A leaked row says where a secret lives, not what it is.
-- =====================================================================================
--
-- SUPERSEDED, 2026-10-02: the rows this file seeded belonged to the kind-named test
-- tenants (`shared`, `dedicated`), which are retired. 20261002-09 registers the real
-- ones, itech and accesspoint, and deletes these hosts. Every migration re-runs on each
-- deploy, so leaving the INSERT here meant each deploy re-created rows pointing at a
-- database and a server that have been deleted, for 09 to remove again moments later.
-- The seeding is gone; the header stays as the record of why the columns exist.

-- Nothing to do.
SELECT 1;
