-- Grace was keeping you writing but not keeping you on your plan.
--
-- 20260821-01 built cp_tenant_platform_limits to mirror check_subscription_active()
-- in auth.py "minus the grace period", and said so in its own header: "grace keeps
-- you writing, it does not keep you on PREMIUM." That was deliberate. It is being
-- reversed, on purpose, and this file is the new decision.
--
-- What it looked like in practice
--
-- A LoanDrift client on PREMIUM, paying by Mobile Money, on time, twice. Their
-- billing period ends at 18:27. At 18:27 they drop to BASIC — Groups disappears,
-- the platform caps tighten — and their bill for the next period is not raised
-- until 01:00 the following morning. They are downgraded roughly seven hours
-- BEFORE the system asks them for any money, for a payment method the platform
-- fully supports.
--
-- Meanwhile check_subscription_active still lets them write for four more days,
-- and send_card_grace_reminders emails them to say they are in grace. So the
-- platform simultaneously told them they were fine and took their features away.
--
-- Splitting grace across the two checks makes no sense from the client's side.
-- Either a late payment is tolerated for four days or it is not. Now it is, for
-- both: the same window, the same rule, both halves in agreement.
--
-- What this does NOT change
--
-- The bill. A lapsed period still raises a PENDING billing row, that row is still
-- owed, and renewal still requires it to be paid. Nobody gets four free days —
-- they get four days to pay for days they are still being charged for. The only
-- thing that moves is when the features switch off, and it moves to exactly where
-- the write-block already was.
--
-- The grace window itself
--
-- Four days, matching SUBSCRIPTION_GRACE_DAYS in both app/src/configs/settings.py
-- and func/shared/settings.py. It is written as a literal here because a view
-- cannot read an environment variable. THE THREE MUST CHANGE TOGETHER: if the env
-- var moves and this does not, the tier and the write-block go back to disagreeing,
-- which is the bug this file exists to close.
--
-- Trials get the same treatment, for the same reason — check_subscription_active
-- already grants trials the grace window, and the view did not.
--
-- Idempotent; safe to re-run on every deploy. DROP before CREATE, per the note in
-- 20260821-01: a later file may add a column and CREATE OR REPLACE cannot.


-- The cp_tenant_platform_limits view is NOT defined here any more.
--
-- It was redefined by three separate files, each dropping and recreating it to
-- change its column set, and every one of them had to drop it because
-- CREATE OR REPLACE cannot add or remove a view's columns. That was survivable
-- until cp_tenant_platform_features started depending on it: a plain DROP then
-- fails outright ("cannot drop view ... because other objects depend on it"),
-- and DROP ... CASCADE would silently take the dependent view with it and leave
-- it gone unless some later file happened to rebuild it.
--
-- So there is now exactly ONE definition, in
-- 20260924-04-coreplatform-a-feature-catalog-for-the-hub.sql, which runs last
-- and rebuilds the dependent view immediately afterwards. If you need to change
-- the view, change it there. Do not reintroduce a copy here.
