-- =====================================================================================
-- Give every permission a structured (resource, action, target, scope), and name the verbs.
--
-- Today a permission is one opaque id, and every rule that needs to know what it DOES matches
-- its name: the Viewer Admin trigger carries ~24 `LOWER(permission_name) LIKE '%get%'` clauses.
-- That is why Loandrift Viewer Admin sees every figure in its app ("... Get Statistics") and
-- Mystoreguard Viewer Admin sees none of its thirty ("... Statistics") -- same role, opposite
-- outcome, decided by wording.
--
-- ADDITIVE and INERT. Grants nothing, revokes nothing, changes no permission id and no
-- application code. It records, for each permission, the parts its id was already built from.
--
-- Covers 513 permissions: the 492 in this repo's seeds plus 21 that exist on the
-- database but in no seed file (LoanDrift agreements, collateral, group lending, restructuring,
-- write-off and repayment reversal). Those were created outside tvs-sqlscript and still need to
-- be committed here; they are included so this migration does not refuse to run on a database
-- that already has them, and so the seeds and the database can be reconciled.
--
-- 488 ids recompose exactly from their parts; 25 spell the same parts in a different
-- word order (`user-groups-get` for `user + get + groups`) and keep the id they already have.
-- Safe to rerun.
-- =====================================================================================

SET search_path TO core_platform;

-- -------------------------------------------------------------------------------------
-- The verbs. Written once for the whole suite, so no rule reads a name again.
--
-- is_read_only and viewer_default are deliberately two columns. `reveal` (ZelosHR sensitive
-- fields) is a read a Viewer Admin must NOT receive, and `calculate` persists a credit score
-- despite sounding harmless. Collapsing "is a read" into "safe for a viewer" is the mistake
-- the LIKE '%get%' rule made.
-- -------------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS core_platform.cp_actions (
    action         TEXT PRIMARY KEY,
    label          TEXT      NOT NULL,
    is_read_only   BOOLEAN   NOT NULL DEFAULT false,
    viewer_default BOOLEAN   NOT NULL DEFAULT false,
    cdatetime      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO core_platform.cp_actions (action, label, is_read_only, viewer_default) VALUES
('add', 'Add', false, false),
('adjust', 'Adjust', false, false),
('approve', 'Approve', false, false),
('assign', 'Assign', false, false),
('backdate', 'Backdate', false, false),
('calculate', 'Calculate', false, false),
('cancel', 'Cancel', false, false),
('change', 'Change', false, false),
('close', 'Close', false, false),
('complete', 'Complete', false, false),
('create', 'Create', false, false),
('delete', 'Delete', false, false),
('deploy', 'Deploy', false, false),
('disburse', 'Disburse', false, false),
('get', 'Get', true, true),
('grant', 'Grant', false, false),
('list', 'List', true, true),
('manage', 'Manage', false, false),
('move', 'Move', false, false),
('pay', 'Pay', false, false),
('permanent-delete', 'Permanent Delete', false, false),
('reconcile', 'Reconcile', false, false),
('refund', 'Refund', false, false),
('reject', 'Reject', false, false),
('release', 'Release', false, false),
('remove', 'Remove', false, false),
('request', 'Request', false, false),
('reset', 'Reset', false, false),
('resolve', 'Resolve', false, false),
('restore', 'Restore', false, false),
('restructure', 'Restructure', false, false),
('reveal', 'Reveal', true, false),
('reverse', 'Reverse', false, false),
('revoke', 'Revoke', false, false),
('share', 'Share', false, false),
('sign', 'Sign', false, false),
('split', 'Split', false, false),
('statistics', 'Statistics', true, true),
('subscribe', 'Subscribe', false, false),
('terminate', 'Terminate', false, false),
('transact', 'Transact', false, false),
('unsubscribe', 'Unsubscribe', false, false),
('update', 'Update', false, false),
('upload', 'Upload', false, false),
('void', 'Void', false, false),
('waive', 'Waive', false, false),
('write-off', 'Write Off', false, false)
ON CONFLICT (action) DO UPDATE SET
    label          = EXCLUDED.label,
    is_read_only   = EXCLUDED.is_read_only,
    viewer_default = EXCLUDED.viewer_default;

-- -------------------------------------------------------------------------------------
-- The parts of each permission. Empty string rather than NULL on purpose: a UNIQUE index over
-- nullable columns does not constrain rows where one is NULL, which is the duplicate this
-- index exists to prevent.
--
-- Two maker-checker pairs are modelled with the decision itself as the resource, so requesting
-- and approving can never collapse into one permission:
--     penalty-waive       + request / approve
--     capturing-write-off + approve
-- -------------------------------------------------------------------------------------
ALTER TABLE core_platform.cp_permissions
    ADD COLUMN IF NOT EXISTS app_prefix   TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS resource_key TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS action       TEXT,
    ADD COLUMN IF NOT EXISTS target       TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS scope        TEXT NOT NULL DEFAULT 'any';

UPDATE core_platform.cp_permissions p SET
    app_prefix = v.app_prefix, resource_key = v.resource_key,
    action = v.action, target = v.target, scope = v.scope
FROM (VALUES
('permission-app-approve-deletion', '', 'app', 'approve', 'deletion', 'any'),
('permission-app-create', '', 'app', 'create', '', 'any'),
('permission-app-delete', '', 'app', 'delete', '', 'any'),
('permission-app-deletion-chat-history-get', '', 'app-deletion-chat-history', 'get', '', 'any'),
('permission-app-get', '', 'app', 'get', '', 'any'),
('permission-app-permanent-delete', '', 'app', 'permanent-delete', '', 'any'),
('permission-app-restore', '', 'app', 'restore', '', 'any'),
('permission-app-statistics-get', '', 'app', 'statistics', '', 'any'),
('permission-app-update', '', 'app', 'update', '', 'any'),
('permission-attendance-adjustments-create', 'zeloshr', 'attendance-adjustments', 'create', '', 'any'),
('permission-attendance-adjustments-get', 'zeloshr', 'attendance-adjustments', 'get', '', 'any'),
('permission-attendance-clock-create', 'zeloshr', 'attendance-clock', 'create', '', 'any'),
('permission-attendance-clock-get', 'zeloshr', 'attendance-clock', 'get', '', 'any'),
('permission-attendance-devices-create', 'zeloshr', 'attendance-devices', 'create', '', 'any'),
('permission-attendance-devices-delete', 'zeloshr', 'attendance-devices', 'delete', '', 'any'),
('permission-attendance-devices-get', 'zeloshr', 'attendance-devices', 'get', '', 'any'),
('permission-attendance-employees-create', 'zeloshr', 'attendance-employees', 'create', '', 'any'),
('permission-attendance-employees-delete', 'zeloshr', 'attendance-employees', 'delete', '', 'any'),
('permission-attendance-employees-get', 'zeloshr', 'attendance-employees', 'get', '', 'any'),
('permission-attendance-employees-update', 'zeloshr', 'attendance-employees', 'update', '', 'any'),
('permission-attendance-records-create', 'zeloshr', 'attendance-records', 'create', '', 'any'),
('permission-attendance-records-delete', 'zeloshr', 'attendance-records', 'delete', '', 'any'),
('permission-attendance-records-get', 'zeloshr', 'attendance-records', 'get', '', 'any'),
('permission-attendance-records-update', 'zeloshr', 'attendance-records', 'update', '', 'any'),
('permission-attendance-team-get', 'zeloshr', 'attendance-team', 'get', '', 'any'),
('permission-attendance-timesheet-get', 'zeloshr', 'attendance-timesheet', 'get', '', 'any'),
('permission-billing-create', '', 'billing', 'create', '', 'any'),
('permission-billing-delete', '', 'billing', 'delete', '', 'any'),
('permission-billing-get', '', 'billing', 'get', '', 'any'),
('permission-billing-make-payment', '', 'billing', 'pay', '', 'any'),
('permission-billing-restore', '', 'billing', 'restore', '', 'any'),
('permission-billing-statistics-get', '', 'billing', 'statistics', '', 'any'),
('permission-business-app-deploy-locations', '', 'business-app', 'deploy', 'locations', 'any'),
('permission-business-app-get', '', 'business-app', 'get', '', 'any'),
('permission-business-app-get-locations', '', 'business-app', 'get', 'locations', 'any'),
('permission-business-app-remove-locations', '', 'business-app', 'remove', 'locations', 'any'),
('permission-business-app-subscribe', '', 'business-app', 'subscribe', '', 'any'),
('permission-business-app-unsubscribe', '', 'business-app', 'unsubscribe', '', 'any'),
('permission-business-approve-deletion', '', 'business', 'approve', 'deletion', 'any'),
('permission-business-create', '', 'business', 'create', '', 'any'),
('permission-business-delete', '', 'business', 'delete', '', 'any'),
('permission-business-deletion-chat-history-get', '', 'business-deletion-chat-history', 'get', '', 'any'),
('permission-business-get', '', 'business', 'get', '', 'any'),
('permission-business-permanent-delete', '', 'business', 'permanent-delete', '', 'any'),
('permission-business-restore', '', 'business', 'restore', '', 'any'),
('permission-business-statistics-get', '', 'business', 'statistics', '', 'any'),
('permission-business-update', '', 'business', 'update', '', 'any'),
('permission-cp-file-delete', 'cp', 'file', 'delete', '', 'any'),
('permission-cp-file-list-documents', 'cp', 'file', 'list', 'documents', 'any'),
('permission-cp-file-update', 'cp', 'file', 'update', '', 'any'),
('permission-cp-file-upload-multiple', 'cp', 'file', 'upload', 'multiple', 'any'),
('permission-cp-logs-delete', 'cp', 'logs', 'delete', '', 'any'),
('permission-cp-logs-get', 'cp', 'logs', 'get', '', 'any'),
('permission-currency-get', '', 'currency', 'get', '', 'any'),
('permission-expense-create', '', 'expense', 'create', '', 'any'),
('permission-expense-delete', '', 'expense', 'delete', '', 'any'),
('permission-expense-get', '', 'expense', 'get', '', 'any'),
('permission-expense-get-statistics', '', 'expense', 'statistics', '', 'any'),
('permission-expense-update', '', 'expense', 'update', '', 'any'),
('permission-group-add-users', '', 'group', 'add', 'users', 'any'),
('permission-group-approve-deletion', '', 'group', 'approve', 'deletion', 'any'),
('permission-group-assign-locations', '', 'group', 'assign', 'locations', 'any'),
('permission-group-assign-roles', '', 'group', 'assign', 'roles', 'any'),
('permission-group-create', '', 'group', 'create', '', 'any'),
('permission-group-delete', '', 'group', 'delete', '', 'any'),
('permission-group-deletion-chat-history-get', '', 'group-deletion-chat-history', 'get', '', 'any'),
('permission-group-get', '', 'group', 'get', '', 'any'),
('permission-group-locations-get', '', 'group-locations', 'get', '', 'any'),
('permission-group-login-settings-get', '', 'group-login-settings', 'get', '', 'any'),
('permission-group-login-settings-update', '', 'group-login-settings', 'update', '', 'any'),
('permission-group-permanent-delete', '', 'group', 'permanent-delete', '', 'any'),
('permission-group-remove-locations', '', 'group', 'remove', 'locations', 'any'),
('permission-group-remove-roles', '', 'group', 'remove', 'roles', 'any'),
('permission-group-remove-users', '', 'group', 'remove', 'users', 'any'),
('permission-group-restore', '', 'group', 'restore', '', 'any'),
('permission-group-statistics-get', '', 'group', 'statistics', '', 'any'),
('permission-group-update', '', 'group', 'update', '', 'any'),
('permission-loandrift-accounting-create', 'loandrift', 'accounting', 'create', '', 'any'),
('permission-loandrift-accounting-delete', 'loandrift', 'accounting', 'delete', '', 'any'),
('permission-loandrift-accounting-get', 'loandrift', 'accounting', 'get', '', 'any'),
('permission-loandrift-accounting-update', 'loandrift', 'accounting', 'update', '', 'any'),
('permission-loandrift-agreements-create', 'loandrift', 'agreements', 'create', '', 'any'),
('permission-loandrift-agreements-get', 'loandrift', 'agreements', 'get', '', 'any'),
('permission-loandrift-agreements-share', 'loandrift', 'agreements', 'share', '', 'any'),
('permission-loandrift-agreements-sign', 'loandrift', 'agreements', 'sign', '', 'any'),
('permission-loandrift-agreements-void', 'loandrift', 'agreements', 'void', '', 'any'),
('permission-loandrift-approval-get', 'loandrift', 'approval', 'get', '', 'any'),
('permission-loandrift-approval-update', 'loandrift', 'approval', 'update', '', 'any'),
('permission-loandrift-calender-get', 'loandrift', 'calender', 'get', '', 'any'),
('permission-loandrift-capturing-approve-reject', 'loandrift', 'capturing', 'reject', '', 'any'),
('permission-loandrift-capturing-complete', 'loandrift', 'capturing', 'complete', '', 'any'),
('permission-loandrift-capturing-create-update', 'loandrift', 'capturing', 'update', '', 'any'),
('permission-loandrift-capturing-delete', 'loandrift', 'capturing', 'delete', '', 'any'),
('permission-loandrift-capturing-get-loan-messages', 'loandrift', 'capturing', 'get', 'loan-messages', 'any'),
('permission-loandrift-capturing-get-statistics', 'loandrift', 'capturing', 'statistics', '', 'any'),
('permission-loandrift-capturing-restructure', 'loandrift', 'capturing', 'restructure', '', 'any'),
('permission-loandrift-capturing-write-off', 'loandrift', 'capturing', 'write-off', '', 'any'),
('permission-loandrift-capturing-write-off-approve', 'loandrift', 'capturing-write-off', 'approve', '', 'any'),
('permission-loandrift-client-approve-deletion', 'loandrift', 'client', 'approve', 'deletion', 'any'),
('permission-loandrift-client-create', 'loandrift', 'client', 'create', '', 'any'),
('permission-loandrift-client-delete', 'loandrift', 'client', 'delete', '', 'any'),
('permission-loandrift-client-get', 'loandrift', 'client', 'get', '', 'any'),
('permission-loandrift-client-get-deletion-chat-history', 'loandrift', 'client', 'get', 'deletion-chat-history', 'any'),
('permission-loandrift-client-get-statistics', 'loandrift', 'client', 'statistics', '', 'any'),
('permission-loandrift-client-update', 'loandrift', 'client', 'update', '', 'any'),
('permission-loandrift-collateral-create', 'loandrift', 'collateral', 'create', '', 'any'),
('permission-loandrift-collateral-delete', 'loandrift', 'collateral', 'delete', '', 'any'),
('permission-loandrift-collateral-get', 'loandrift', 'collateral', 'get', '', 'any'),
('permission-loandrift-collateral-update', 'loandrift', 'collateral', 'update', '', 'any'),
('permission-loandrift-collections-create', 'loandrift', 'collections', 'create', '', 'any'),
('permission-loandrift-collections-delete', 'loandrift', 'collections', 'delete', '', 'any'),
('permission-loandrift-collections-get', 'loandrift', 'collections', 'get', '', 'any'),
('permission-loandrift-collections-update', 'loandrift', 'collections', 'update', '', 'any'),
('permission-loandrift-credit-score-adjust', 'loandrift', 'credit-score', 'adjust', '', 'any'),
('permission-loandrift-credit-score-calculate', 'loandrift', 'credit-score', 'calculate', '', 'any'),
('permission-loandrift-credit-score-create', 'loandrift', 'credit-score', 'create', '', 'any'),
('permission-loandrift-credit-score-get', 'loandrift', 'credit-score', 'get', '', 'any'),
('permission-loandrift-credit-score-settings-get', 'loandrift', 'credit-score-settings', 'get', '', 'any'),
('permission-loandrift-credit-score-settings-update', 'loandrift', 'credit-score-settings', 'update', '', 'any'),
('permission-loandrift-dashboard-get-chart-data', 'loandrift', 'dashboard', 'get', 'chart-data', 'any'),
('permission-loandrift-dashboard-get-statistics', 'loandrift', 'dashboard', 'statistics', '', 'any'),
('permission-loandrift-disbursement-disburse', 'loandrift', 'disbursement', 'disburse', '', 'any'),
('permission-loandrift-disbursement-get', 'loandrift', 'disbursement', 'get', '', 'any'),
('permission-loandrift-disbursement-update', 'loandrift', 'disbursement', 'update', '', 'any'),
('permission-loandrift-expenses-create', 'loandrift', 'expenses', 'create', '', 'any'),
('permission-loandrift-expenses-delete', 'loandrift', 'expenses', 'delete', '', 'any'),
('permission-loandrift-expenses-get', 'loandrift', 'expenses', 'get', '', 'any'),
('permission-loandrift-expenses-get-activity-logs', 'loandrift', 'expenses', 'get', 'activity-logs', 'any'),
('permission-loandrift-expenses-get-statistics', 'loandrift', 'expenses', 'statistics', '', 'any'),
('permission-loandrift-expenses-update', 'loandrift', 'expenses', 'update', '', 'any'),
('permission-loandrift-file-delete', 'loandrift', 'file', 'delete', '', 'any'),
('permission-loandrift-file-list-documents', 'loandrift', 'file', 'list', 'documents', 'any'),
('permission-loandrift-file-update', 'loandrift', 'file', 'update', '', 'any'),
('permission-loandrift-file-upload-multiple', 'loandrift', 'file', 'upload', 'multiple', 'any'),
('permission-loandrift-groups-create', 'loandrift', 'groups', 'create', '', 'any'),
('permission-loandrift-groups-get', 'loandrift', 'groups', 'get', '', 'any'),
('permission-loandrift-groups-update', 'loandrift', 'groups', 'update', '', 'any'),
('permission-loandrift-investment-complete', 'loandrift', 'investment', 'complete', '', 'any'),
('permission-loandrift-investment-create', 'loandrift', 'investment', 'create', '', 'any'),
('permission-loandrift-investment-delete', 'loandrift', 'investment', 'delete', '', 'any'),
('permission-loandrift-investment-get', 'loandrift', 'investment', 'get', '', 'any'),
('permission-loandrift-investment-get-statistics', 'loandrift', 'investment', 'statistics', '', 'any'),
('permission-loandrift-investment-terminate', 'loandrift', 'investment', 'terminate', '', 'any'),
('permission-loandrift-investment-update', 'loandrift', 'investment', 'update', '', 'any'),
('permission-loandrift-loan-registration-create-existing-client', 'loandrift', 'loan-registration', 'create', 'existing-client', 'any'),
('permission-loandrift-loan-registration-create-new-client', 'loandrift', 'loan-registration', 'create', 'new-client', 'any'),
('permission-loandrift-loan-registration-delete', 'loandrift', 'loan-registration', 'delete', '', 'any'),
('permission-loandrift-loan-registration-get', 'loandrift', 'loan-registration', 'get', '', 'any'),
('permission-loandrift-loan-registration-get-statistics', 'loandrift', 'loan-registration', 'statistics', '', 'any'),
('permission-loandrift-loan-registration-update', 'loandrift', 'loan-registration', 'update', '', 'any'),
('permission-loandrift-locations-get', 'loandrift', 'locations', 'get', '', 'any'),
('permission-loandrift-logs-delete', 'loandrift', 'logs', 'delete', '', 'any'),
('permission-loandrift-logs-get', 'loandrift', 'logs', 'get', '', 'any'),
('permission-loandrift-penalty-add', 'loandrift', 'penalty', 'add', '', 'any'),
('permission-loandrift-penalty-create', 'loandrift', 'penalty', 'create', '', 'any'),
('permission-loandrift-penalty-get', 'loandrift', 'penalty', 'get', '', 'any'),
('permission-loandrift-penalty-settings-get', 'loandrift', 'penalty-settings', 'get', '', 'any'),
('permission-loandrift-penalty-settings-update', 'loandrift', 'penalty-settings', 'update', '', 'any'),
('permission-loandrift-penalty-waive', 'loandrift', 'penalty', 'waive', '', 'any'),
('permission-loandrift-penalty-waive-approve', 'loandrift', 'penalty-waive', 'approve', '', 'any'),
('permission-loandrift-penalty-waive-request', 'loandrift', 'penalty-waive', 'request', '', 'any'),
('permission-loandrift-repayment-auto', 'loandrift', 'repayment-auto', 'manage', '', 'any'),
('permission-loandrift-repayment-create', 'loandrift', 'repayment', 'create', '', 'any'),
('permission-loandrift-repayment-delete', 'loandrift', 'repayment', 'delete', '', 'any'),
('permission-loandrift-repayment-get', 'loandrift', 'repayment', 'get', '', 'any'),
('permission-loandrift-repayment-get-payment-dates', 'loandrift', 'repayment', 'get', 'payment-dates', 'any'),
('permission-loandrift-repayment-get-statistics', 'loandrift', 'repayment', 'statistics', '', 'any'),
('permission-loandrift-repayment-refund', 'loandrift', 'repayment', 'refund', '', 'any'),
('permission-loandrift-repayment-reverse', 'loandrift', 'repayment', 'reverse', '', 'any'),
('permission-loandrift-repayment-update', 'loandrift', 'repayment', 'update', '', 'any'),
('permission-loandrift-reports-get', 'loandrift', 'reports', 'get', '', 'any'),
('permission-loandrift-savings-close', 'loandrift', 'savings', 'close', '', 'any'),
('permission-loandrift-savings-create', 'loandrift', 'savings', 'create', '', 'any'),
('permission-loandrift-savings-delete', 'loandrift', 'savings', 'delete', '', 'any'),
('permission-loandrift-savings-get', 'loandrift', 'savings', 'get', '', 'any'),
('permission-loandrift-savings-get-statistics', 'loandrift', 'savings', 'statistics', '', 'any'),
('permission-loandrift-savings-transact', 'loandrift', 'savings', 'transact', '', 'any'),
('permission-loandrift-savings-update', 'loandrift', 'savings', 'update', '', 'any'),
('permission-loandrift-settings-create', 'loandrift', 'settings', 'create', '', 'any'),
('permission-loandrift-settings-delete', 'loandrift', 'settings', 'delete', '', 'any'),
('permission-loandrift-settings-get', 'loandrift', 'settings', 'get', '', 'any'),
('permission-loandrift-settings-update', 'loandrift', 'settings', 'update', '', 'any'),
('permission-location-approve-deletion', '', 'location', 'approve', 'deletion', 'any'),
('permission-location-create', '', 'location', 'create', '', 'any'),
('permission-location-delete', '', 'location', 'delete', '', 'any'),
('permission-location-deletion-chat-history-get', '', 'location-deletion-chat-history', 'get', '', 'any'),
('permission-location-get', '', 'location', 'get', '', 'any'),
('permission-location-permanent-delete', '', 'location', 'permanent-delete', '', 'any'),
('permission-location-restore', '', 'location', 'restore', '', 'any'),
('permission-location-statistics-get', '', 'location', 'statistics', '', 'any'),
('permission-location-update', '', 'location', 'update', '', 'any'),
('permission-msg-affiliates-create', 'msg', 'affiliates', 'create', '', 'any'),
('permission-msg-affiliates-delete', 'msg', 'affiliates', 'delete', '', 'any'),
('permission-msg-affiliates-get', 'msg', 'affiliates', 'get', '', 'any'),
('permission-msg-affiliates-statistics', 'msg', 'affiliates', 'statistics', '', 'any'),
('permission-msg-affiliates-update', 'msg', 'affiliates', 'update', '', 'any'),
('permission-msg-appointments-create', 'msg', 'appointments', 'create', '', 'any'),
('permission-msg-appointments-delete', 'msg', 'appointments', 'delete', '', 'any'),
('permission-msg-appointments-get', 'msg', 'appointments', 'get', '', 'any'),
('permission-msg-appointments-update', 'msg', 'appointments', 'update', '', 'any'),
('permission-msg-collection-reconcile', 'msg', 'collection', 'reconcile', '', 'any'),
('permission-msg-credit-score-adjust', 'msg', 'credit-score', 'adjust', '', 'any'),
('permission-msg-credit-score-settings', 'msg', 'credit-score-settings', 'manage', '', 'any'),
('permission-msg-custom-fields-get', 'msg', 'custom-fields', 'get', '', 'any'),
('permission-msg-customers-create', 'msg', 'customers', 'create', '', 'any'),
('permission-msg-customers-delete', 'msg', 'customers', 'delete', '', 'any'),
('permission-msg-customers-get', 'msg', 'customers', 'get', '', 'any'),
('permission-msg-customers-statistics', 'msg', 'customers', 'statistics', '', 'any'),
('permission-msg-customers-update', 'msg', 'customers', 'update', '', 'any'),
('permission-msg-deliveries-create', 'msg', 'deliveries', 'create', '', 'any'),
('permission-msg-deliveries-delete', 'msg', 'deliveries', 'delete', '', 'any'),
('permission-msg-deliveries-get', 'msg', 'deliveries', 'get', '', 'any'),
('permission-msg-deliveries-statistics', 'msg', 'deliveries', 'statistics', '', 'any'),
('permission-msg-deliveries-update', 'msg', 'deliveries', 'update', '', 'any'),
('permission-msg-ecommerce-create', 'msg', 'ecommerce', 'create', '', 'any'),
('permission-msg-ecommerce-delete', 'msg', 'ecommerce', 'delete', '', 'any'),
('permission-msg-ecommerce-get', 'msg', 'ecommerce', 'get', '', 'any'),
('permission-msg-ecommerce-update', 'msg', 'ecommerce', 'update', '', 'any'),
('permission-msg-estimate-templates-create', 'msg', 'estimate-templates', 'create', '', 'any'),
('permission-msg-estimate-templates-delete', 'msg', 'estimate-templates', 'delete', '', 'any'),
('permission-msg-estimate-templates-get', 'msg', 'estimate-templates', 'get', '', 'any'),
('permission-msg-estimate-templates-statistics', 'msg', 'estimate-templates', 'statistics', '', 'any'),
('permission-msg-estimate-templates-update', 'msg', 'estimate-templates', 'update', '', 'any'),
('permission-msg-estimates-create', 'msg', 'estimates', 'create', '', 'any'),
('permission-msg-estimates-delete', 'msg', 'estimates', 'delete', '', 'any'),
('permission-msg-estimates-get', 'msg', 'estimates', 'get', '', 'any'),
('permission-msg-estimates-statistics', 'msg', 'estimates', 'statistics', '', 'any'),
('permission-msg-estimates-update', 'msg', 'estimates', 'update', '', 'any'),
('permission-msg-expenses-create', 'msg', 'expenses', 'create', '', 'any'),
('permission-msg-expenses-delete', 'msg', 'expenses', 'delete', '', 'any'),
('permission-msg-expenses-get', 'msg', 'expenses', 'get', '', 'any'),
('permission-msg-expenses-get-statistics', 'msg', 'expenses', 'statistics', '', 'any'),
('permission-msg-expenses-update', 'msg', 'expenses', 'update', '', 'any'),
('permission-msg-file-delete', 'msg', 'file', 'delete', '', 'any'),
('permission-msg-file-list-documents', 'msg', 'file', 'list', 'documents', 'any'),
('permission-msg-file-update', 'msg', 'file', 'update', '', 'any'),
('permission-msg-file-upload-multiple', 'msg', 'file', 'upload', 'multiple', 'any'),
('permission-msg-gift-cards-create', 'msg', 'gift-cards', 'create', '', 'any'),
('permission-msg-gift-cards-delete', 'msg', 'gift-cards', 'delete', '', 'any'),
('permission-msg-gift-cards-get', 'msg', 'gift-cards', 'get', '', 'any'),
('permission-msg-gift-cards-statistics', 'msg', 'gift-cards', 'statistics', '', 'any'),
('permission-msg-gift-cards-update', 'msg', 'gift-cards', 'update', '', 'any'),
('permission-msg-guarantor-create', 'msg', 'guarantor', 'create', '', 'any'),
('permission-msg-guarantor-delete', 'msg', 'guarantor', 'delete', '', 'any'),
('permission-msg-guarantor-get', 'msg', 'guarantor', 'get', '', 'any'),
('permission-msg-guarantor-update', 'msg', 'guarantor', 'update', '', 'any'),
('permission-msg-installment-plan-approve', 'msg', 'installment-plan', 'approve', '', 'any'),
('permission-msg-installment-plan-cancel', 'msg', 'installment-plan', 'cancel', '', 'any'),
('permission-msg-installment-plan-close-refund', 'msg', 'installment-plan', 'refund', '', 'any'),
('permission-msg-installment-plan-get', 'msg', 'installment-plan', 'get', '', 'any'),
('permission-msg-installment-plan-pay', 'msg', 'installment-plan', 'pay', '', 'any'),
('permission-msg-installment-plan-refund-payment', 'msg', 'installment-plan', 'refund', 'payment', 'any'),
('permission-msg-installment-plan-statistics', 'msg', 'installment-plan', 'statistics', '', 'any'),
('permission-msg-installment-plan-waive', 'msg', 'installment-plan', 'waive', '', 'any'),
('permission-msg-installment-policy-create', 'msg', 'installment-policy', 'create', '', 'any'),
('permission-msg-installment-policy-delete', 'msg', 'installment-policy', 'delete', '', 'any'),
('permission-msg-installment-policy-get', 'msg', 'installment-policy', 'get', '', 'any'),
('permission-msg-installment-policy-statistics', 'msg', 'installment-policy', 'statistics', '', 'any'),
('permission-msg-installment-policy-update', 'msg', 'installment-policy', 'update', '', 'any'),
('permission-msg-invoices-create', 'msg', 'invoices', 'create', '', 'any'),
('permission-msg-invoices-delete', 'msg', 'invoices', 'delete', '', 'any'),
('permission-msg-invoices-get', 'msg', 'invoices', 'get', '', 'any'),
('permission-msg-invoices-statistics', 'msg', 'invoices', 'statistics', '', 'any'),
('permission-msg-invoices-update', 'msg', 'invoices', 'update', '', 'any'),
('permission-msg-logs-delete', 'msg', 'logs', 'delete', '', 'any'),
('permission-msg-logs-get', 'msg', 'logs', 'get', '', 'any'),
('permission-msg-loyalty-create', 'msg', 'loyalty', 'create', '', 'any'),
('permission-msg-loyalty-delete', 'msg', 'loyalty', 'delete', '', 'any'),
('permission-msg-loyalty-get', 'msg', 'loyalty', 'get', '', 'any'),
('permission-msg-loyalty-update', 'msg', 'loyalty', 'update', '', 'any'),
('permission-msg-messaging-create', 'msg', 'messaging', 'create', '', 'any'),
('permission-msg-messaging-delete', 'msg', 'messaging', 'delete', '', 'any'),
('permission-msg-messaging-get', 'msg', 'messaging', 'get', '', 'any'),
('permission-msg-messaging-statistics', 'msg', 'messaging', 'statistics', '', 'any'),
('permission-msg-messaging-update', 'msg', 'messaging', 'update', '', 'any'),
('permission-msg-pricing-rule-create', 'msg', 'pricing-rule', 'create', '', 'any'),
('permission-msg-pricing-rule-delete', 'msg', 'pricing-rule', 'delete', '', 'any'),
('permission-msg-pricing-rule-get', 'msg', 'pricing-rule', 'get', '', 'any'),
('permission-msg-pricing-rule-statistics', 'msg', 'pricing-rule', 'statistics', '', 'any'),
('permission-msg-pricing-rule-update', 'msg', 'pricing-rule', 'update', '', 'any'),
('permission-msg-product-metadata-create', 'msg', 'product-metadata', 'create', '', 'any'),
('permission-msg-product-metadata-delete', 'msg', 'product-metadata', 'delete', '', 'any'),
('permission-msg-product-metadata-get', 'msg', 'product-metadata', 'get', '', 'any'),
('permission-msg-product-metadata-statistics', 'msg', 'product-metadata', 'statistics', '', 'any'),
('permission-msg-product-metadata-update', 'msg', 'product-metadata', 'update', '', 'any'),
('permission-msg-product-price-create', 'msg', 'product-price', 'create', '', 'any'),
('permission-msg-product-price-delete', 'msg', 'product-price', 'delete', '', 'any'),
('permission-msg-product-price-get', 'msg', 'product-price', 'get', '', 'any'),
('permission-msg-product-price-statistics', 'msg', 'product-price', 'statistics', '', 'any'),
('permission-msg-product-price-update', 'msg', 'product-price', 'update', '', 'any'),
('permission-msg-products-adjust-delivery', 'msg', 'products', 'adjust', 'delivery', 'any'),
('permission-msg-products-create', 'msg', 'products', 'create', '', 'any'),
('permission-msg-products-delete', 'msg', 'products', 'delete', '', 'any'),
('permission-msg-products-get', 'msg', 'products', 'get', '', 'any'),
('permission-msg-products-move-batch', 'msg', 'products', 'move', 'batch', 'any'),
('permission-msg-products-split', 'msg', 'products', 'split', '', 'any'),
('permission-msg-products-statistics', 'msg', 'products', 'statistics', '', 'any'),
('permission-msg-products-update', 'msg', 'products', 'update', '', 'any'),
('permission-msg-promo-codes-create', 'msg', 'promo-codes', 'create', '', 'any'),
('permission-msg-promo-codes-delete', 'msg', 'promo-codes', 'delete', '', 'any'),
('permission-msg-promo-codes-get', 'msg', 'promo-codes', 'get', '', 'any'),
('permission-msg-promo-codes-statistics', 'msg', 'promo-codes', 'statistics', '', 'any'),
('permission-msg-promo-codes-update', 'msg', 'promo-codes', 'update', '', 'any'),
('permission-msg-purchase-orders-backdate', 'msg', 'purchase-orders', 'backdate', '', 'any'),
('permission-msg-purchase-orders-create', 'msg', 'purchase-orders', 'create', '', 'any'),
('permission-msg-purchase-orders-delete', 'msg', 'purchase-orders', 'delete', '', 'any'),
('permission-msg-purchase-orders-get', 'msg', 'purchase-orders', 'get', '', 'any'),
('permission-msg-purchase-orders-statistics', 'msg', 'purchase-orders', 'statistics', '', 'any'),
('permission-msg-purchase-orders-update', 'msg', 'purchase-orders', 'update', '', 'any'),
('permission-msg-reports-get', 'msg', 'reports', 'get', '', 'any'),
('permission-msg-return-policy-create', 'msg', 'return-policy', 'create', '', 'any'),
('permission-msg-return-policy-delete', 'msg', 'return-policy', 'delete', '', 'any'),
('permission-msg-return-policy-get', 'msg', 'return-policy', 'get', '', 'any'),
('permission-msg-return-policy-statistics', 'msg', 'return-policy', 'statistics', '', 'any'),
('permission-msg-return-policy-update', 'msg', 'return-policy', 'update', '', 'any'),
('permission-msg-stock-takes-create', 'msg', 'stock-takes', 'create', '', 'any'),
('permission-msg-stock-takes-delete', 'msg', 'stock-takes', 'delete', '', 'any'),
('permission-msg-stock-takes-get', 'msg', 'stock-takes', 'get', '', 'any'),
('permission-msg-stock-takes-resolve', 'msg', 'stock-takes', 'resolve', '', 'any'),
('permission-msg-stock-takes-reverse', 'msg', 'stock-takes', 'reverse', '', 'any'),
('permission-msg-stock-takes-statistics', 'msg', 'stock-takes', 'statistics', '', 'any'),
('permission-msg-store-config-create', 'msg', 'store-config', 'create', '', 'any'),
('permission-msg-store-config-get', 'msg', 'store-config', 'get', '', 'any'),
('permission-msg-store-credit-get', 'msg', 'store-credit', 'get', '', 'any'),
('permission-msg-store-credit-manage', 'msg', 'store-credit', 'manage', '', 'any'),
('permission-msg-store-products-create', 'msg', 'store-products', 'create', '', 'any'),
('permission-msg-store-products-delete', 'msg', 'store-products', 'delete', '', 'any'),
('permission-msg-store-products-get', 'msg', 'store-products', 'get', '', 'any'),
('permission-msg-store-products-statistics', 'msg', 'store-products', 'statistics', '', 'any'),
('permission-msg-store-products-update', 'msg', 'store-products', 'update', '', 'any'),
('permission-msg-store-returns-approve', 'msg', 'store-returns', 'approve', '', 'any'),
('permission-msg-store-returns-create', 'msg', 'store-returns', 'create', '', 'any'),
('permission-msg-store-returns-get', 'msg', 'store-returns', 'get', '', 'any'),
('permission-msg-store-returns-statistics', 'msg', 'store-returns', 'statistics', '', 'any'),
('permission-msg-store-returns-update', 'msg', 'store-returns', 'update', '', 'any'),
('permission-msg-store-sales-backdate', 'msg', 'store-sales', 'backdate', '', 'any'),
('permission-msg-store-sales-cancel', 'msg', 'store-sales', 'cancel', '', 'any'),
('permission-msg-store-sales-create', 'msg', 'store-sales', 'create', '', 'any'),
('permission-msg-store-sales-delete', 'msg', 'store-sales', 'delete', '', 'any'),
('permission-msg-store-sales-get', 'msg', 'store-sales', 'get', '', 'any'),
('permission-msg-store-sales-release-goods', 'msg', 'store-sales', 'release', 'goods', 'any'),
('permission-msg-store-sales-statistics', 'msg', 'store-sales', 'statistics', '', 'any'),
('permission-msg-store-sales-update', 'msg', 'store-sales', 'update', '', 'any'),
('permission-msg-store-transfers-approve', 'msg', 'store-transfers', 'approve', '', 'any'),
('permission-msg-store-transfers-create', 'msg', 'store-transfers', 'create', '', 'any'),
('permission-msg-store-transfers-delete', 'msg', 'store-transfers', 'delete', '', 'any'),
('permission-msg-store-transfers-get', 'msg', 'store-transfers', 'get', '', 'any'),
('permission-msg-store-transfers-statistics', 'msg', 'store-transfers', 'statistics', '', 'any'),
('permission-msg-store-transfers-update', 'msg', 'store-transfers', 'update', '', 'any'),
('permission-msg-suppliers-create', 'msg', 'suppliers', 'create', '', 'any'),
('permission-msg-suppliers-delete', 'msg', 'suppliers', 'delete', '', 'any'),
('permission-msg-suppliers-get', 'msg', 'suppliers', 'get', '', 'any'),
('permission-msg-suppliers-statistics', 'msg', 'suppliers', 'statistics', '', 'any'),
('permission-msg-suppliers-update', 'msg', 'suppliers', 'update', '', 'any'),
('permission-msg-tasks-approve', 'msg', 'tasks', 'approve', '', 'any'),
('permission-msg-tasks-create', 'msg', 'tasks', 'create', '', 'any'),
('permission-msg-tasks-delete', 'msg', 'tasks', 'delete', '', 'any'),
('permission-msg-tasks-get', 'msg', 'tasks', 'get', '', 'any'),
('permission-msg-tasks-manage-templates', 'msg', 'tasks', 'manage', 'templates', 'any'),
('permission-msg-tasks-statistics', 'msg', 'tasks', 'statistics', '', 'any'),
('permission-msg-tasks-update', 'msg', 'tasks', 'update', '', 'any'),
('permission-msg-tax-rule-create', 'msg', 'tax-rule', 'create', '', 'any'),
('permission-msg-tax-rule-delete', 'msg', 'tax-rule', 'delete', '', 'any'),
('permission-msg-tax-rule-get', 'msg', 'tax-rule', 'get', '', 'any'),
('permission-msg-tax-rule-statistics', 'msg', 'tax-rule', 'statistics', '', 'any'),
('permission-msg-tax-rule-update', 'msg', 'tax-rule', 'update', '', 'any'),
('permission-msg-taxes-create', 'msg', 'taxes', 'create', '', 'any'),
('permission-msg-taxes-delete', 'msg', 'taxes', 'delete', '', 'any'),
('permission-msg-taxes-get', 'msg', 'taxes', 'get', '', 'any'),
('permission-msg-taxes-statistics', 'msg', 'taxes', 'statistics', '', 'any'),
('permission-msg-taxes-update', 'msg', 'taxes', 'update', '', 'any'),
('permission-msg-warehouse-config-create', 'msg', 'warehouse-config', 'create', '', 'any'),
('permission-msg-warehouse-config-get', 'msg', 'warehouse-config', 'get', '', 'any'),
('permission-msg-warehouse-products-create', 'msg', 'warehouse-products', 'create', '', 'any'),
('permission-msg-warehouse-products-delete', 'msg', 'warehouse-products', 'delete', '', 'any'),
('permission-msg-warehouse-products-get', 'msg', 'warehouse-products', 'get', '', 'any'),
('permission-msg-warehouse-products-statistics', 'msg', 'warehouse-products', 'statistics', '', 'any'),
('permission-msg-warehouse-products-update', 'msg', 'warehouse-products', 'update', '', 'any'),
('permission-msg-warehouse-transfers-approve', 'msg', 'warehouse-transfers', 'approve', '', 'any'),
('permission-msg-warehouse-transfers-create', 'msg', 'warehouse-transfers', 'create', '', 'any'),
('permission-msg-warehouse-transfers-delete', 'msg', 'warehouse-transfers', 'delete', '', 'any'),
('permission-msg-warehouse-transfers-get', 'msg', 'warehouse-transfers', 'get', '', 'any'),
('permission-msg-warehouse-transfers-statistics', 'msg', 'warehouse-transfers', 'statistics', '', 'any'),
('permission-msg-warehouse-transfers-update', 'msg', 'warehouse-transfers', 'update', '', 'any'),
('permission-msg-workflow-templates-statistics', 'msg', 'workflow-templates', 'statistics', '', 'any'),
('permission-organization-approve-deletion', '', 'organization', 'approve', 'deletion', 'any'),
('permission-organization-create', '', 'organization', 'create', '', 'any'),
('permission-organization-delete', '', 'organization', 'delete', '', 'any'),
('permission-organization-deletion-chat-history-get', '', 'organization-deletion-chat-history', 'get', '', 'any'),
('permission-organization-get', '', 'organization', 'get', '', 'any'),
('permission-organization-permanent-delete', '', 'organization', 'permanent-delete', '', 'any'),
('permission-organization-restore', '', 'organization', 'restore', '', 'any'),
('permission-organization-statistics-get', '', 'organization', 'statistics', '', 'any'),
('permission-organization-update', '', 'organization', 'update', '', 'any'),
('permission-permission-get', '', 'permission', 'get', '', 'any'),
('permission-role-approve-deletion', '', 'role', 'approve', 'deletion', 'any'),
('permission-role-create', '', 'role', 'create', '', 'any'),
('permission-role-delete', '', 'role', 'delete', '', 'any'),
('permission-role-deletion-chat-history-get', '', 'role-deletion-chat-history', 'get', '', 'any'),
('permission-role-get', '', 'role', 'get', '', 'any'),
('permission-role-permanent-delete', '', 'role', 'permanent-delete', '', 'any'),
('permission-role-restore', '', 'role', 'restore', '', 'any'),
('permission-role-statistics-get', '', 'role', 'statistics', '', 'any'),
('permission-role-update', '', 'role', 'update', '', 'any'),
('permission-security-get', '', 'security', 'get', '', 'any'),
('permission-security-update', '', 'security', 'update', '', 'any'),
('permission-settings-create', '', 'settings', 'create', '', 'any'),
('permission-settings-delete', '', 'settings', 'delete', '', 'any'),
('permission-settings-get', '', 'settings', 'get', '', 'any'),
('permission-settings-permanent-delete', '', 'settings', 'permanent-delete', '', 'any'),
('permission-settings-restore', '', 'settings', 'restore', '', 'any'),
('permission-settings-statistics-get', '', 'settings', 'statistics', '', 'any'),
('permission-settings-update', '', 'settings', 'update', '', 'any'),
('permission-subscription-get', '', 'subscription', 'get', '', 'any'),
('permission-subscription-update', '', 'subscription', 'update', '', 'any'),
('permission-theme-get', '', 'theme', 'get', '', 'any'),
('permission-theme-update', '', 'theme', 'update', '', 'any'),
('permission-user-add-to-groups', '', 'user', 'add', 'to-groups', 'any'),
('permission-user-assign-locations', '', 'user', 'assign', 'locations', 'any'),
('permission-user-assign-roles', '', 'user', 'assign', 'roles', 'any'),
('permission-user-change-password', '', 'user', 'change', 'password', 'any'),
('permission-user-create', '', 'user', 'create', '', 'any'),
('permission-user-delete', '', 'user', 'delete', '', 'any'),
('permission-user-deletion-chat-history-get', '', 'user-deletion-chat-history', 'get', '', 'any'),
('permission-user-get', '', 'user', 'get', '', 'any'),
('permission-user-get-locations', '', 'user', 'get', 'locations', 'any'),
('permission-user-get-own', '', 'user', 'get', '', 'own'),
('permission-user-grant-access', '', 'user', 'grant', 'access', 'any'),
('permission-user-groups-get', '', 'user-groups', 'get', '', 'any'),
('permission-user-groups-get-own', '', 'user-groups', 'get', '', 'own'),
('permission-user-locations-get', '', 'user-locations', 'get', '', 'any'),
('permission-user-locations-get-own', '', 'user-locations', 'get', '', 'own'),
('permission-user-login-settings-get', '', 'user-login-settings', 'get', '', 'any'),
('permission-user-login-settings-update', '', 'user-login-settings', 'update', '', 'any'),
('permission-user-permanent-delete', '', 'user', 'permanent-delete', '', 'any'),
('permission-user-remove-from-groups', '', 'user', 'remove', 'from-groups', 'any'),
('permission-user-remove-locations', '', 'user', 'remove', 'locations', 'any'),
('permission-user-remove-roles', '', 'user', 'remove', 'roles', 'any'),
('permission-user-reset-password', '', 'user', 'reset', 'password', 'any'),
('permission-user-resource-types-with-roles-get', '', 'user-resource-types-with-roles', 'get', '', 'any'),
('permission-user-restore', '', 'user', 'restore', '', 'any'),
('permission-user-revoke-access', '', 'user', 'revoke', 'access', 'any'),
('permission-user-roles-get', '', 'user-roles', 'get', '', 'any'),
('permission-user-roles-get-own', '', 'user-roles', 'get', '', 'own'),
('permission-user-statistics-get', '', 'user', 'statistics', '', 'any'),
('permission-user-update', '', 'user', 'update', '', 'any'),
('permission-user-update-own', '', 'user', 'update', '', 'own'),
('permission-user-upload-profile-picture', '', 'user', 'upload', 'profile-picture', 'any'),
('permission-zeloshr-attendance-create', 'zeloshr', 'attendance', 'create', '', 'any'),
('permission-zeloshr-attendance-delete', 'zeloshr', 'attendance', 'delete', '', 'any'),
('permission-zeloshr-attendance-get', 'zeloshr', 'attendance', 'get', '', 'any'),
('permission-zeloshr-attendance-update', 'zeloshr', 'attendance', 'update', '', 'any'),
('permission-zeloshr-audit-create', 'zeloshr', 'audit', 'create', '', 'any'),
('permission-zeloshr-audit-delete', 'zeloshr', 'audit', 'delete', '', 'any'),
('permission-zeloshr-audit-get', 'zeloshr', 'audit', 'get', '', 'any'),
('permission-zeloshr-audit-update', 'zeloshr', 'audit', 'update', '', 'any'),
('permission-zeloshr-branches-create', 'zeloshr', 'branches', 'create', '', 'any'),
('permission-zeloshr-branches-delete', 'zeloshr', 'branches', 'delete', '', 'any'),
('permission-zeloshr-branches-get', 'zeloshr', 'branches', 'get', '', 'any'),
('permission-zeloshr-branches-update', 'zeloshr', 'branches', 'update', '', 'any'),
('permission-zeloshr-custom-field-values-create', 'zeloshr', 'custom-field-values', 'create', '', 'any'),
('permission-zeloshr-custom-field-values-delete', 'zeloshr', 'custom-field-values', 'delete', '', 'any'),
('permission-zeloshr-custom-field-values-get', 'zeloshr', 'custom-field-values', 'get', '', 'any'),
('permission-zeloshr-custom-field-values-update', 'zeloshr', 'custom-field-values', 'update', '', 'any'),
('permission-zeloshr-custom-fields-create', 'zeloshr', 'custom-fields', 'create', '', 'any'),
('permission-zeloshr-custom-fields-delete', 'zeloshr', 'custom-fields', 'delete', '', 'any'),
('permission-zeloshr-custom-fields-get', 'zeloshr', 'custom-fields', 'get', '', 'any'),
('permission-zeloshr-custom-fields-update', 'zeloshr', 'custom-fields', 'update', '', 'any'),
('permission-zeloshr-dashboard-create', 'zeloshr', 'dashboard', 'create', '', 'any'),
('permission-zeloshr-dashboard-delete', 'zeloshr', 'dashboard', 'delete', '', 'any'),
('permission-zeloshr-dashboard-get', 'zeloshr', 'dashboard', 'get', '', 'any'),
('permission-zeloshr-dashboard-update', 'zeloshr', 'dashboard', 'update', '', 'any'),
('permission-zeloshr-departments-create', 'zeloshr', 'departments', 'create', '', 'any'),
('permission-zeloshr-departments-delete', 'zeloshr', 'departments', 'delete', '', 'any'),
('permission-zeloshr-departments-get', 'zeloshr', 'departments', 'get', '', 'any'),
('permission-zeloshr-departments-update', 'zeloshr', 'departments', 'update', '', 'any'),
('permission-zeloshr-disciplinary-create', 'zeloshr', 'disciplinary', 'create', '', 'any'),
('permission-zeloshr-disciplinary-delete', 'zeloshr', 'disciplinary', 'delete', '', 'any'),
('permission-zeloshr-disciplinary-get', 'zeloshr', 'disciplinary', 'get', '', 'any'),
('permission-zeloshr-disciplinary-update', 'zeloshr', 'disciplinary', 'update', '', 'any'),
('permission-zeloshr-documents-create', 'zeloshr', 'documents', 'create', '', 'any'),
('permission-zeloshr-documents-delete', 'zeloshr', 'documents', 'delete', '', 'any'),
('permission-zeloshr-documents-get', 'zeloshr', 'documents', 'get', '', 'any'),
('permission-zeloshr-documents-update', 'zeloshr', 'documents', 'update', '', 'any'),
('permission-zeloshr-employee-create', 'zeloshr', 'employee', 'create', '', 'any'),
('permission-zeloshr-employee-delete', 'zeloshr', 'employee', 'delete', '', 'any'),
('permission-zeloshr-employee-get', 'zeloshr', 'employee', 'get', '', 'any'),
('permission-zeloshr-employee-update', 'zeloshr', 'employee', 'update', '', 'any'),
('permission-zeloshr-leave-create', 'zeloshr', 'leave', 'create', '', 'any'),
('permission-zeloshr-leave-delete', 'zeloshr', 'leave', 'delete', '', 'any'),
('permission-zeloshr-leave-get', 'zeloshr', 'leave', 'get', '', 'any'),
('permission-zeloshr-leave-update', 'zeloshr', 'leave', 'update', '', 'any'),
('permission-zeloshr-lifecycle-create', 'zeloshr', 'lifecycle', 'create', '', 'any'),
('permission-zeloshr-lifecycle-delete', 'zeloshr', 'lifecycle', 'delete', '', 'any'),
('permission-zeloshr-lifecycle-get', 'zeloshr', 'lifecycle', 'get', '', 'any'),
('permission-zeloshr-lifecycle-update', 'zeloshr', 'lifecycle', 'update', '', 'any'),
('permission-zeloshr-onboarding-create', 'zeloshr', 'onboarding', 'create', '', 'any'),
('permission-zeloshr-onboarding-delete', 'zeloshr', 'onboarding', 'delete', '', 'any'),
('permission-zeloshr-onboarding-get', 'zeloshr', 'onboarding', 'get', '', 'any'),
('permission-zeloshr-onboarding-update', 'zeloshr', 'onboarding', 'update', '', 'any'),
('permission-zeloshr-org-create', 'zeloshr', 'org', 'create', '', 'any'),
('permission-zeloshr-org-delete', 'zeloshr', 'org', 'delete', '', 'any'),
('permission-zeloshr-org-get', 'zeloshr', 'org', 'get', '', 'any'),
('permission-zeloshr-org-update', 'zeloshr', 'org', 'update', '', 'any'),
('permission-zeloshr-performance-create', 'zeloshr', 'performance', 'create', '', 'any'),
('permission-zeloshr-performance-delete', 'zeloshr', 'performance', 'delete', '', 'any'),
('permission-zeloshr-performance-get', 'zeloshr', 'performance', 'get', '', 'any'),
('permission-zeloshr-performance-update', 'zeloshr', 'performance', 'update', '', 'any'),
('permission-zeloshr-recruitment-create', 'zeloshr', 'recruitment', 'create', '', 'any'),
('permission-zeloshr-recruitment-delete', 'zeloshr', 'recruitment', 'delete', '', 'any'),
('permission-zeloshr-recruitment-get', 'zeloshr', 'recruitment', 'get', '', 'any'),
('permission-zeloshr-recruitment-update', 'zeloshr', 'recruitment', 'update', '', 'any'),
('permission-zeloshr-sensitive-fields-reveal', 'zeloshr', 'sensitive-fields', 'reveal', '', 'any')
) AS v(id, app_prefix, resource_key, action, target, scope)
WHERE p.id = v.id;

-- -------------------------------------------------------------------------------------
-- Guards. A permission this migration does not know about keeps action NULL, and the Viewer
-- Admin rule that follows would silently skip it -- the same class of bug being fixed here.
-- So fail the deploy and name the rows instead. If this fires, somebody added a permission
-- straight to the database again: add it to the catalogue AND to the seeds.
-- -------------------------------------------------------------------------------------
DO $$
DECLARE uncovered TEXT;
BEGIN
    SELECT string_agg(id, ', ' ORDER BY id) INTO uncovered
    FROM core_platform.cp_permissions
    WHERE action IS NULL AND delete_status = 'NOT_DELETED';
    IF uncovered IS NOT NULL THEN
        RAISE WARNING 'cp_permissions rows with no action yet -- add them to the catalogue: %', uncovered;
    END IF;
END $$;

DO $$
DECLARE orphan TEXT;
BEGIN
    SELECT string_agg(DISTINCT p.action, ', ') INTO orphan
    FROM core_platform.cp_permissions p
    LEFT JOIN core_platform.cp_actions a ON a.action = p.action
    WHERE p.action IS NOT NULL AND a.action IS NULL;
    IF orphan IS NOT NULL THEN
        RAISE EXCEPTION 'cp_permissions uses actions absent from cp_actions: %', orphan;
    END IF;
END $$;

-- -------------------------------------------------------------------------------------
-- Now that every row is populated, make the shape enforceable. The FK turns a typo (`aprove`)
-- or a second word for an existing verb (`view` beside `get`) into an error rather than a new
-- verb nobody grants.
--
-- `action` is deliberately left NULLABLE, and the guard above only warns.
--
-- migrations/shared applies in ordinal filename order, so anything added later in the day or on
-- a later date runs AFTER this file -- and LoanDrift migrations are landing daily, inserting
-- permissions with no action. A NOT NULL here would fail the very next one and break somebody
-- else's deploy, not ours. Renumbering this file only postpones that to tomorrow.
--
-- So: populate now, constrain later. Turning on NOT NULL is a separate migration, to be written
-- once the seeds and the app migrations supply `action` themselves. Until then the FK below
-- still rejects a typo'd verb whenever one IS given, which is the guardrail that matters most.
-- -------------------------------------------------------------------------------------

ALTER TABLE core_platform.cp_permissions
    DROP CONSTRAINT IF EXISTS fk_cp_permissions_cp_actions_action;
ALTER TABLE core_platform.cp_permissions
    ADD CONSTRAINT fk_cp_permissions_cp_actions_action
    FOREIGN KEY (action) REFERENCES core_platform.cp_actions (action);

-- One permission per (app, resource, action, target, scope). This is the constraint that would
-- have caught `permission-user-locations-get` sitting beside `permission-user-get-locations` --
-- two ids for one thing, one of them enforced nowhere.
CREATE UNIQUE INDEX IF NOT EXISTS ux_cp_permissions_resource_action
    ON core_platform.cp_permissions (app_prefix, resource_key, action, target, scope)
    WHERE delete_status = 'NOT_DELETED';
