// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Trovesuite.Database.Attendance;

#nullable disable

namespace Trovesuite.Database.Attendance.Migrations
{
    [DbContext(typeof(AttendanceDbContext))]
    [Migration("20260922175627_SyncAttendanceModelSnapshot")]
    partial class SyncAttendanceModelSnapshot
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("attendance")
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Trovesuite.Database.Attendance.Entities.AttAdjustment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("AttendanceDate")
                        .HasColumnType("date")
                        .HasColumnName("attendance_date");

                    b.Property<Guid?>("AttendanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("attendance_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedById")
                        .HasColumnType("text")
                        .HasColumnName("created_by_id");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("OrgId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("org_id");

                    b.Property<Guid?>("OriginalPunchId")
                        .HasColumnType("uuid")
                        .HasColumnName("original_punch_id");

                    b.Property<TimeOnly?>("PunchTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("punch_time");

                    b.Property<string>("PunchType")
                        .HasColumnType("text")
                        .HasColumnName("punch_type");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("text")
                        .HasColumnName("updated_by_id");

                    b.HasKey("Id")
                        .HasName("pk_att_adjustments");

                    b.HasIndex("TenantId", "OrgId", "EmployeeId", "AttendanceDate")
                        .HasDatabaseName("ix_att_adjustments_tenant_id_org_id_employee_id_attendance_date");

                    b.ToTable("att_adjustments", "attendance");
                });

            modelBuilder.Entity("Trovesuite.Database.Attendance.Entities.AttAttendanceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("AttendanceDate")
                        .HasColumnType("date")
                        .HasColumnName("attendance_date");

                    b.Property<bool>("AutoClosed")
                        .HasColumnType("boolean")
                        .HasColumnName("auto_closed");

                    b.Property<string>("BranchName")
                        .HasColumnType("text")
                        .HasColumnName("branch_name");

                    b.Property<string>("CaptureSource")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("web")
                        .HasColumnName("capture_source");

                    b.Property<TimeOnly?>("ClockIn")
                        .HasColumnType("time without time zone")
                        .HasColumnName("clock_in");

                    b.Property<TimeOnly?>("ClockOut")
                        .HasColumnType("time without time zone")
                        .HasColumnName("clock_out");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedById")
                        .HasColumnType("text")
                        .HasColumnName("created_by_id");

                    b.Property<string>("DepartmentName")
                        .HasColumnType("text")
                        .HasColumnName("department_name");

                    b.Property<string>("EmployeeCode")
                        .HasColumnType("text")
                        .HasColumnName("employee_code");

                    b.Property<string>("EmployeeFullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("employee_full_name");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<decimal?>("HoursWorked")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("hours_worked");

                    b.Property<bool>("IsAdjusted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_adjusted");

                    b.Property<string>("OrgId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("org_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("text")
                        .HasColumnName("updated_by_id");

                    b.HasKey("Id")
                        .HasName("pk_att_attendance_records");

                    b.HasIndex("TenantId", "OrgId", "AttendanceDate")
                        .HasDatabaseName("ix_att_attendance_records_tenant_id_org_id_attendance_date");

                    b.HasIndex("TenantId", "OrgId", "EmployeeId", "AttendanceDate")
                        .IsUnique()
                        .HasDatabaseName("ix_att_attendance_records_tenant_id_org_id_employee_id_attenda");

                    b.ToTable("att_attendance_records", "attendance");
                });

            modelBuilder.Entity("Trovesuite.Database.Attendance.Entities.AttDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedById")
                        .HasColumnType("text")
                        .HasColumnName("created_by_id");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_enabled");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Location")
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<string>("Model")
                        .HasColumnType("text")
                        .HasColumnName("model");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("OrgId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("org_id");

                    b.Property<string>("Serial")
                        .HasColumnType("text")
                        .HasColumnName("serial");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("text")
                        .HasColumnName("updated_by_id");

                    b.Property<string>("Vendor")
                        .HasColumnType("text")
                        .HasColumnName("vendor");

                    b.HasKey("Id")
                        .HasName("pk_att_devices");

                    b.HasIndex("Serial")
                        .IsUnique()
                        .HasDatabaseName("ix_att_devices_serial")
                        .HasFilter("serial IS NOT NULL AND serial <> ''");

                    b.HasIndex("TenantId", "OrgId", "Name")
                        .HasDatabaseName("ix_att_devices_tenant_id_org_id_name");

                    b.ToTable("att_devices", "attendance");
                });

            modelBuilder.Entity("Trovesuite.Database.Attendance.Entities.AttEmployee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BranchName")
                        .HasColumnType("text")
                        .HasColumnName("branch_name");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedById")
                        .HasColumnType("text")
                        .HasColumnName("created_by_id");

                    b.Property<string>("DepartmentName")
                        .HasColumnType("text")
                        .HasColumnName("department_name");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("employee_code");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsHeadOfDepartment")
                        .HasColumnType("boolean")
                        .HasColumnName("is_head_of_department");

                    b.Property<bool>("IsLineManager")
                        .HasColumnType("boolean")
                        .HasColumnName("is_line_manager");

                    b.Property<string>("JobTitle")
                        .HasColumnType("text")
                        .HasColumnName("job_title");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("MiddleName")
                        .HasColumnType("text")
                        .HasColumnName("middle_name");

                    b.Property<string>("OrgId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("org_id");

                    b.Property<Guid?>("ReportsToEmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("reports_to_employee_id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("text")
                        .HasColumnName("updated_by_id");

                    b.HasKey("Id")
                        .HasName("pk_att_employees");

                    b.HasIndex("TenantId", "OrgId", "EmployeeCode")
                        .IsUnique()
                        .HasDatabaseName("ix_att_employees_tenant_id_org_id_employee_code");

                    b.HasIndex("TenantId", "OrgId", "ReportsToEmployeeId")
                        .HasDatabaseName("ix_att_employees_tenant_id_org_id_reports_to_employee_id");

                    b.ToTable("att_employees", "attendance");
                });

            modelBuilder.Entity("Trovesuite.Database.Attendance.Entities.AttPunch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AttendanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("attendance_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedById")
                        .HasColumnType("text")
                        .HasColumnName("created_by_id");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<bool>("IsSuperseded")
                        .HasColumnType("boolean")
                        .HasColumnName("is_superseded");

                    b.Property<string>("OrgId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("org_id");

                    b.Property<string>("PunchType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("punch_type");

                    b.Property<DateTimeOffset>("PunchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("punched_at");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("web")
                        .HasColumnName("source");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("text")
                        .HasColumnName("updated_by_id");

                    b.HasKey("Id")
                        .HasName("pk_att_punches");

                    b.HasIndex("AttendanceId")
                        .HasDatabaseName("ix_att_punches_attendance_id");

                    b.HasIndex("DeviceId", "EmployeeId", "PunchedAt")
                        .IsUnique()
                        .HasDatabaseName("ix_att_punches_device_id_employee_id_punched_at")
                        .HasFilter("device_id IS NOT NULL AND is_superseded = false");

                    b.HasIndex("TenantId", "OrgId", "EmployeeId", "PunchedAt")
                        .HasDatabaseName("ix_att_punches_tenant_id_org_id_employee_id_punched_at");

                    b.ToTable("att_punches", "attendance");
                });
#pragma warning restore 612, 618
        }
    }
}
