// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Trovesuite.Database.Attendance;

#nullable disable

namespace Trovesuite.Database.Attendance.Migrations
{
    [DbContext(typeof(AttendanceDbContext))]
    [Migration("20260901150000_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasDefaultSchema("attendance");
#pragma warning restore 612, 618
        }
    }
}
